// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/balance.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;

namespace Conf
{
    public partial class BalanceCfg
    {
        /// <summary>Enemy HP scale</summary>
        [JsonProperty("hpScale")] public float HpScale { get; set; }
        /// <summary>Enemy damage scale</summary>
        [JsonProperty("dmgScale")] public double DmgScale { get; set; }
        /// <summary>Gold bonus</summary>
        [JsonProperty("goldBonus")] public double GoldBonus { get; set; }
        /// <summary>Enemy level offset</summary>
        [JsonProperty("enemyLevel")] public short EnemyLevel { get; set; }
        /// <summary>Spawn interval</summary>
        [JsonProperty("spawnInterval")] public Duration SpawnInterval { get; set; }
        /// <summary>XP curve</summary>
        [JsonProperty("xpCurve")] public List<int>? XpCurve { get; set; }
    }

    #region Trifles

    #endregion
}
