// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/chapter.json5

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;
using Conf.Enums;

namespace Conf
{
    public partial class ChapterArray : List<ChapterCfg?> { }

    public partial class ChapterCfg
    {
        [JsonProperty("id")] public string Id { get; set; } = string.Empty;
        [JsonProperty("title")] public string Title { get; set; } = string.Empty;
        [JsonProperty("hero")] public XRef<HeroCfgId, HeroCfg> Hero { get; set; }
        [JsonProperty("monsters")] public List<XRef<MonsterCfgId, MonsterCfg>>? Monsters { get; set; }
        [JsonProperty("recommended")] public List<HeroClass>? Recommended { get; set; }
        [JsonProperty("timeLimit")] public Duration TimeLimit { get; set; }
        [JsonProperty("waves")] public List<long>? Waves { get; set; }
    }

    #region Trifles

    public partial class ChapterArray : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this)
            {
                v1?.BindRefs(atlas);
            }
        }
    }

    public partial class ChapterCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Hero = atlas.HeroTable.RefLookup(Hero.CfgId);
            if (Monsters is not null)
            {
                for (var i1 = 0; i1 < Monsters.Count; i1++)
                {
                    Monsters[i1] = atlas.MonsterTable.RefLookup(Monsters[i1].CfgId);
                }
            }
        }
    }

    #endregion
}
