// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/drop.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;
using Conf.Enums;

namespace Conf
{
    [Serializable]
    public partial struct DropCfgId
    {
        public long Value;
        public readonly DropCfg Cfg => ConfigAtlas.Instance.DropTable[Value]!;
    }

    public partial class DropTable : Dictionary<DropCfgId, DropCfg> { }

    public partial class DropCfg
    {
        [JsonProperty("id")] public DropCfgId Id { get; set; }
        /// <summary>Drop name</summary>
        [JsonProperty("name")] public string Name { get; set; } = string.Empty;
        /// <summary>Gold</summary>
        [JsonProperty("gold")] public MinMax<int> Gold { get; set; }
        /// <summary>Bonus rate</summary>
        [JsonProperty("bonusRate")] public MinMax<float> BonusRate { get; set; }
        /// <summary>Despawn time</summary>
        [JsonProperty("despawn")] public MinMax<Duration> Despawn { get; set; }
        /// <summary>Items</summary>
        [JsonProperty("items")] public WeightedPool<XRef<ItemCfgId, ItemCfg>>? Items { get; set; }
        /// <summary>Coins</summary>
        [JsonProperty("coins")] public WeightedPool<long>? Coins { get; set; }
        /// <summary>Titles</summary>
        [JsonProperty("titles")] public WeightedPool<string>? Titles { get; set; }
        /// <summary>Rarity</summary>
        [JsonProperty("rarity")] public WeightedPool<Rarity>? Rarity { get; set; }
        /// <summary>Buff time</summary>
        [JsonProperty("buffTime")] public WeightedPool<Duration>? BuffTime { get; set; }
    }

    public partial class DropTable
    {
        public bool TryLookup(DropCfgId cfgId, [NotNullWhen(true)] out DropCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this, "DropTable", out cfg);
        }

        public DropCfg? Lookup(DropCfgId cfgId)
        {
            return ConfigAtlas.Lookup(cfgId, this, "DropTable");
        }

        internal XRef<DropCfgId, DropCfg> RefLookup(DropCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup(cfgId, this, "DropTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(DropCfgIdJsonConverter))]
    [TypeConverter(typeof(DropCfgIdTypeConverter))]
    public partial struct DropCfgId : IEquatable<DropCfgId>, IZero
    {
        public DropCfgId(long value) { Value = value; }
        public static implicit operator DropCfgId(long value) => new() { Value = value };
        public static implicit operator long(DropCfgId obj) => obj.Value;

        public override readonly bool Equals(object? obj) => obj is DropCfgId other && Equals(other);
        public readonly bool Equals(DropCfgId other) => Value == other.Value;
        public override readonly int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(DropCfgId left, DropCfgId right) => left.Value == right.Value;
        public static bool operator !=(DropCfgId left, DropCfgId right) => left.Value != right.Value;

        public override readonly string ToString() => Value.ToString();
        public readonly bool IsZero => Value == 0;
    }

    class DropCfgIdJsonConverter : ValueWrapperJsonConverter<DropCfgId, long>
    {
        protected override DropCfgId Create(long value) => value;
        protected override long GetValue(DropCfgId obj) => obj.Value;
    }

    class DropCfgIdTypeConverter : ValueWrapperTypeConverter<DropCfgId, long>
    {
        protected override DropCfgId Create(long value) => value;
    }

    public partial class DropTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val is not null) val.Id = key;
            }
        }
    }

    public partial class DropTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                v1?.BindRefs(atlas);
            }
        }
    }

    public partial class DropCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            if (Items?.Items is not null)
            {
                for (var i = 0; i < Items.Items.Length; i++)
                {
                    Items.Items[i] = atlas.ItemTable.RefLookup(Items.Items[i].CfgId);
                }
            }
        }
    }

    #endregion
}
