// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: skill (virtual table)

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;
using Conf.Enums;

namespace Conf
{
    [Serializable]
    public partial struct SkillCfgId
    {
        public string Value;
        public readonly SkillCfg Cfg => ConfigAtlas.Instance.SkillTable[Value]!;
    }

    public partial class SkillTable : Dictionary<SkillCfgId, SkillCfg> { }

    public partial class SkillCfg
    {
        [JsonProperty("id")] public SkillCfgId Id { get; set; } = string.Empty;
        /// <summary>Skill name</summary>
        [JsonProperty("name")] public string Name { get; set; } = string.Empty;
        /// <summary>Cooldown</summary>
        [JsonProperty("cooldown")] public Duration Cooldown { get; set; }
        /// <summary>Mana cost</summary>
        [JsonProperty("mana")] public int Mana { get; set; }
        /// <summary>School</summary>
        [JsonProperty("school")] public Element School { get; set; }
        /// <summary>Source</summary>
        [JsonProperty("src")] public string Src { get; set; } = string.Empty;
        /// <summary>Damage</summary>
        [JsonProperty("damage")] public MinMax<int> Damage { get; set; }
        /// <summary>Buffs</summary>
        [JsonProperty("buffs")] public Dictionary<string, Skill_BuffsEntry>? Buffs { get; set; }
        [JsonProperty("radius")] public double Radius { get; set; }
    }

    // Skill_BuffsEntry represents $.*.buffs.*
    public partial class Skill_BuffsEntry
    {
        /// <summary>Stacks</summary>
        [JsonProperty("stacks")] public sbyte Stacks { get; set; }
        /// <summary>Buff duration</summary>
        [JsonProperty("time")] public Duration Time { get; set; }
        /// <summary>Granted by</summary>
        [JsonProperty("source")] public XRef<ItemCfgId, ItemCfg> Source { get; set; }
    }

    public partial class SkillTable
    {
        public bool TryLookup(SkillCfgId cfgId, [NotNullWhen(true)] out SkillCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this, "SkillTable", out cfg);
        }

        public SkillCfg? Lookup(SkillCfgId cfgId)
        {
            return ConfigAtlas.Lookup(cfgId, this, "SkillTable");
        }

        internal XRef<SkillCfgId, SkillCfg> RefLookup(SkillCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup(cfgId, this, "SkillTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(SkillCfgIdJsonConverter))]
    [TypeConverter(typeof(SkillCfgIdTypeConverter))]
    public partial struct SkillCfgId : IEquatable<SkillCfgId>, IZero
    {
        public SkillCfgId(string value) { Value = value; }
        public static implicit operator SkillCfgId(string value) => new() { Value = value };
        public static implicit operator string(SkillCfgId obj) => obj.Value ?? string.Empty;

        public override readonly bool Equals(object? obj) => obj is SkillCfgId other && Equals(other);
        public readonly bool Equals(SkillCfgId other) => (Value ?? string.Empty) == (other.Value ?? string.Empty);
        public override readonly int GetHashCode() => (Value ?? string.Empty).GetHashCode();

        public static bool operator ==(SkillCfgId left, SkillCfgId right) => left.Equals(right);
        public static bool operator !=(SkillCfgId left, SkillCfgId right) => !left.Equals(right);

        public override readonly string ToString() => Value ?? string.Empty;
        public bool IsZero => string.IsNullOrEmpty(Value);
    }

    class SkillCfgIdJsonConverter : ValueWrapperJsonConverter<SkillCfgId, string>
    {
        protected override SkillCfgId Create(string value) => value;
        protected override string GetValue(SkillCfgId obj) => obj.Value ?? string.Empty;
    }

    class SkillCfgIdTypeConverter : ValueWrapperTypeConverter<SkillCfgId, string>
    {
        protected override SkillCfgId Create(string value) => value;
    }

    public partial class SkillTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val is not null) val.Id = key;
            }
        }
    }

    public partial class SkillTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                v1?.BindRefs(atlas);
            }
        }
    }

    public partial class SkillCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            if (Buffs is not null)
            {
                foreach (var v1 in Buffs.Values)
                {
                    v1?.BindRefs(atlas);
                }
            }
        }
    }

    public partial class Skill_BuffsEntry
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Source = atlas.ItemTable.RefLookup(Source.CfgId);
        }
    }

    #endregion
}
