// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.

#if TOOLS

#nullable enable

namespace Conf.Editor
{
    public partial class ArchmageEditorPlugin
    {
        static void RegisterDefaultCfgIdChoices(ConfigAtlas atlas)
        {
            DropCfgIdChoices.Register(atlas.DropTable, v => $"{v}");
            HeroCfgIdChoices.Register(atlas.HeroTable, v => $"{v}");
            ItemCfgIdChoices.Register(atlas.ItemTable, v => $"{v}");
            MonsterCfgIdChoices.Register(atlas.MonsterTable, v => $"{v}");
            RaceCfgIdChoices.Register(atlas.RaceTable, v => $"{v}");
            RegionCfgIdChoices.Register(atlas.RegionTable, v => $"{v}");
            SkillCfgIdChoices.Register(atlas.SkillTable, v => $"{v}");
        }
    }
}

#endif
