// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.

#nullable enable

using Godot;

namespace Conf.Editor
{
    /// <summary>
    /// The hints of exported config ID properties. Pass a member of this class and the member of the same name of
    /// <see cref="CfgIdPropType"/> to <c>[Export]</c>, and the Inspector shows the property as a dropdown, for example
    /// <c>[Export(CfgIdPropHint.Hero, CfgIdPropType.Hero)]</c>.
    /// </summary>
    public static class CfgIdPropHint
    {
        public const PropertyHint Drop = PropertyHint.None;
        public const PropertyHint DropArray = PropertyHint.TypeString;
        public const PropertyHint Hero = PropertyHint.None;
        public const PropertyHint HeroArray = PropertyHint.TypeString;
        public const PropertyHint Item = PropertyHint.None;
        public const PropertyHint ItemArray = PropertyHint.TypeString;
        public const PropertyHint Monster = PropertyHint.None;
        public const PropertyHint MonsterArray = PropertyHint.TypeString;
        public const PropertyHint Race = PropertyHint.None;
        public const PropertyHint RaceArray = PropertyHint.TypeString;
        public const PropertyHint Region = PropertyHint.None;
        public const PropertyHint RegionArray = PropertyHint.TypeString;
        public const PropertyHint Skill = PropertyHint.None;
        public const PropertyHint SkillArray = PropertyHint.TypeString;
    }

    /// <summary>
    /// The hint strings of exported config ID properties. See <see cref="CfgIdPropHint"/>.
    /// </summary>
    public static class CfgIdPropType
    {
        /// <summary>For a <c>long</c> field or property.</summary>
        public const string Drop = "DropCfgId";
        /// <summary>For a <c>long[]</c> field or property.</summary>
        public const string DropArray = "2/0:DropCfgId";

        /// <summary>For a <c>long</c> field or property.</summary>
        public const string Hero = "HeroCfgId";
        /// <summary>For a <c>long[]</c> field or property.</summary>
        public const string HeroArray = "2/0:HeroCfgId";

        /// <summary>For a <c>long</c> field or property.</summary>
        public const string Item = "ItemCfgId";
        /// <summary>For a <c>long[]</c> field or property.</summary>
        public const string ItemArray = "2/0:ItemCfgId";

        /// <summary>For a <c>long</c> field or property.</summary>
        public const string Monster = "MonsterCfgId";
        /// <summary>For a <c>long[]</c> field or property.</summary>
        public const string MonsterArray = "2/0:MonsterCfgId";

        /// <summary>For a <c>string</c> field or property.</summary>
        public const string Race = "RaceCfgId";
        /// <summary>For a <c>string[]</c> field or property.</summary>
        public const string RaceArray = "4/0:RaceCfgId";

        /// <summary>For a <c>string</c> field or property.</summary>
        public const string Region = "RegionCfgId";
        /// <summary>For a <c>string[]</c> field or property.</summary>
        public const string RegionArray = "4/0:RegionCfgId";

        /// <summary>For a <c>string</c> field or property.</summary>
        public const string Skill = "SkillCfgId";
        /// <summary>For a <c>string[]</c> field or property.</summary>
        public const string SkillArray = "4/0:SkillCfgId";
    }

#if TOOLS
    public partial class ArchmageEditorPlugin
    {
        static void RegisterDefaultCfgIdChoices(ConfigAtlas atlas)
        {
            DropCfgIdChoices.Register(atlas.DropTable, v => $"{v}");
            HeroCfgIdChoices.Register(atlas.HeroTable, v => $"{v}");
            ItemCfgIdChoices.Register(atlas.ItemTable, v => $"{v}");
            MonsterCfgIdChoices.Register(atlas.MonsterTable, v => $"{v}");
            RaceCfgIdChoices.Register(atlas.RaceTable, v => $"{v}");
            RegionCfgIdChoices.Register(atlas.RegionTable, v => $"{v}");
            SkillCfgIdChoices.Register(atlas.SkillTable, v => $"{v}");
        }
    }
#endif
}
