// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/drop.xlsx

#if TOOLS

#nullable enable

using System;

namespace Conf.Editor
{
    public static class DropCfgIdChoices
    {
        public static void Register(DropTable tbl, Func<long, string> format) =>
            CfgIdChoices.RegisterInt("DropCfgId", tbl.Keys, id => id.Value, format);
    }
}

#endif
