// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/hero.xlsx

#if TOOLS

#nullable enable

using System;

namespace Conf.Editor
{
    public static class HeroCfgIdChoices
    {
        public static void Register(HeroTable tbl, Func<long, string> format) =>
            CfgIdChoices.RegisterInt("HeroCfgId", tbl.Keys, id => id.Value, format);
    }
}

#endif
