// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/item.xlsx

#if TOOLS

#nullable enable

using System;

namespace Conf.Editor
{
    public static class ItemCfgIdChoices
    {
        public static void Register(ItemTable tbl, Func<long, string> format) =>
            CfgIdChoices.RegisterInt("ItemCfgId", tbl.Keys, id => id.Value, format);
    }
}

#endif
