// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/monster.json

#if TOOLS

#nullable enable

using System;

namespace Conf.Editor
{
    public static class MonsterCfgIdChoices
    {
        public static void Register(MonsterTable tbl, Func<long, string> format) =>
            CfgIdChoices.RegisterInt("MonsterCfgId", tbl.Keys, id => id.Value, format);
    }
}

#endif
