// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/world.xlsx::Race

#if TOOLS

#nullable enable

using System;

namespace Conf.Editor
{
    public static class RaceCfgIdChoices
    {
        public static void Register(RaceTable tbl, Func<string, string> format) =>
            CfgIdChoices.RegisterStr("RaceCfgId", tbl.Keys, id => id.Value, format);
    }
}

#endif
