// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/world.xlsx::Region

#if TOOLS

#nullable enable

using System;

namespace Conf.Editor
{
    public static class RegionCfgIdChoices
    {
        public static void Register(RegionTable tbl, Func<string, string> format) =>
            CfgIdChoices.RegisterStr("RegionCfgId", tbl.Keys, id => id.Value, format);
    }
}

#endif
