// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: skill (virtual table)

#if TOOLS

#nullable enable

using System;

namespace Conf.Editor
{
    public static class SkillCfgIdChoices
    {
        public static void Register(SkillTable tbl, Func<string, string> format) =>
            CfgIdChoices.RegisterStr("SkillCfgId", tbl.Keys, id => id.Value, format);
    }
}

#endif
