// Code generated by (shadowopera) archmage. DO NOT EDIT.

#nullable enable

using System;
using System.Collections.Generic;
using Shadop.Archmage.Sdk;

namespace Conf
{
    /// <summary>
    /// Holds all game configuration tables and provides cross-table reference binding.
    /// </summary>
    public partial class ConfigAtlas : IAtlas
    {
        /// <summary>
        /// The active ConfigAtlas. It must be set before calling any XxxCfgId.Cfg.
        /// </summary>
        public static ConfigAtlas Instance = null!;

        Dictionary<string, AtlasItem> _m = null!;
        public AtlasExtension Extension { get; private set; }
        /// <summary>
        /// The version info of the config repo at export time.
        /// </summary>
        public VersionInfo? DataVersion { get; private set; }

        public CharacterArray CharacterArray { get; set; }
        public GameCfg GameCfg { get; set; }
        public HeroTable HeroTable { get; set; }
        public ItemTable ItemTable { get; set; }
        public MagicTable MagicTable { get; set; }
        public Matrix2Table Matrix2Table { get; set; }
        public PropFloatsCfg PropFloatsCfg { get; set; }
        public RaceTable RaceTable { get; set; }
        public RefTable RefTable { get; set; }
        public StringTable StringTable { get; set; }
        public VtItemXTable VtItemXTable { get; set; }
        public VtSkillTable VtSkillTable { get; set; }
        public WeaponRuneTable WeaponRuneTable { get; set; }

        public ConfigAtlas()
        {
            PubtypeCheck();
            Extension = new AtlasExtension();
            CharacterArray = new CharacterArray();
            GameCfg = new GameCfg();
            HeroTable = new HeroTable();
            ItemTable = new ItemTable();
            MagicTable = new MagicTable();
            Matrix2Table = new Matrix2Table();
            PropFloatsCfg = new PropFloatsCfg();
            RaceTable = new RaceTable();
            RefTable = new RefTable();
            StringTable = new StringTable();
            VtItemXTable = new VtItemXTable();
            VtSkillTable = new VtSkillTable();
            WeaponRuneTable = new WeaponRuneTable();
            BuildMap();
        }

        void BuildMap()
        {
            _m = new Dictionary<string, AtlasItem>
            {
                { "character", new AtlasItem { Cfg = CharacterArray, Mapping = "unique" } },
                { "game", new AtlasItem { Cfg = GameCfg, Mapping = "single" } },
                { "hero", new AtlasItem { Cfg = HeroTable, Mapping = "unique" } },
                { "Item", new AtlasItem { Cfg = ItemTable, Mapping = "unique" } },
                { "Magic", new AtlasItem { Cfg = MagicTable, Mapping = "unique" } },
                { "matrix2", new AtlasItem { Cfg = Matrix2Table, Mapping = "unique" } },
                { "prop_floats", new AtlasItem { Cfg = PropFloatsCfg, Mapping = "single" } },
                { "Race", new AtlasItem { Cfg = RaceTable, Mapping = "unique" } },
                { "ref", new AtlasItem { Cfg = RefTable, Mapping = "unique" } },
                { "string", new AtlasItem { Cfg = StringTable, Mapping = "unique" } },
                { "vtItemX", new AtlasItem { Cfg = VtItemXTable, Mapping = "multiple" } },
                { "vtSkill", new AtlasItem { Cfg = VtSkillTable, Mapping = "multiple" } },
                { "weapon-rune", new AtlasItem { Cfg = WeaponRuneTable, Mapping = "unique" } },
            };
        }

        /// <summary>For internal use only.</summary>
        public void SetDataVersion(VersionInfo? v)
        {
            DataVersion = v;
        }

        /// <summary>For internal use only.</summary>
        public void BindRefs()
        {
            var keys = new List<string>(_m.Keys);
            keys.Sort(StringComparer.OrdinalIgnoreCase);
            foreach (var k in keys)
            {
                if (_m[k].Cfg is IRefBinder binder)
                    binder.BindRefs(this);
            }
        }

        /// <summary>
        /// Returns the internal map of config-name to AtlasItem.
        /// </summary>
        public Dictionary<string, AtlasItem> AtlasItems()
        {
            return _m;
        }

        /// <summary>
        /// Called after all config data has been loaded and refs bound. Delegates to
        /// AtlasExtension.OnLoaded. For internal use only.
        /// </summary>
        public void OnLoaded()
        {
            Extension.OnLoaded(this);
        }

        internal static XRef<V, T> MakeXRef<V, T>(V cfgId, T? refValue)
            where V : notnull
            where T : class
            => new(cfgId, refValue);

        internal static bool TryLookup<K, V>(K cfgId, Dictionary<K, V> tbl, string tblName, out V? cfg)
            where K : notnull
            where V : class
        {
            if (tbl.TryGetValue(cfgId, out cfg))
                return true;
            cfg = null;
            return false;
        }

        internal static V? Lookup<K, V>(K cfgId, Dictionary<K, V> tbl, string tblName)
            where K : notnull
            where V : class
        {
            if (cfgId is IZero z && z.IsZero)
                return null;
            if (tbl.TryGetValue(cfgId, out var cfg))
                return cfg;
            throw new KeyNotFoundException(string.Format("{0}: config entry not found for Id {1}", tblName, cfgId));
        }

        static void PubtypeCheck()
        {
            var m = new HashSet<string>();
            m.Add("Rab"); // string
            if (m.Count != 1)
                throw new Exception("conflicting pubtype detected");
        }
    }

    interface IRefBinder
    {
        void BindRefs(ConfigAtlas atlas);
    }
}
