// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/character.json5

#nullable enable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class CharacterArray : List<CharacterCfg?>
    {
        // Definition only.
    }

    public partial class CharacterCfg
    {
        [JsonProperty("id")]
        public string Id { get; set; } = null!;
        /// <summary>
        /// name config
        /// </summary>
        [JsonProperty("name")]
        public L10n Name { get; set; }
        /// <summary>
        /// race config
        /// </summary>
        [JsonProperty("race")]
        public XRef<string, RaceCfg> Race { get; set; }
        /// <summary>
        /// health config
        /// </summary>
        [JsonProperty("health")]
        public long Health { get; set; }
        [JsonProperty("attack")]
        public double Attack { get; set; }
        [JsonProperty("isPlayable")]
        public bool IsPlayable { get; set; }
        [JsonProperty("skills")]
        public List<string>? Skills { get; set; }
        /// <summary>
        /// my runes
        /// </summary>
        [JsonProperty("runes")]
        public List<XRef<long, WeaponRuneCfg>>? Runes { get; set; }
        [JsonProperty("ultimateSkill")]
        public long UltimateSkill { get; set; }
        [JsonProperty("ref-crude")]
        public Character_RefCrude? RefCrude { get; set; }
    }

    // Character_RefCrude represents $.*['ref-crude']
    public partial class Character_RefCrude
    {
        [JsonProperty("r1")]
        public long R1 { get; set; }
        [JsonProperty("r2")]
        public string R2 { get; set; } = null!;
    }

    #region Trifles

    public partial class CharacterArray : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this)
            {
                if (v1 != null)
                    v1.BindRefs(atlas);
            }
        }
    }

    public partial class CharacterCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Race = atlas.RaceTable.RefLookup(Race.RawValue);
            if (Runes != null)
            {
                for (var i1 = 0; i1 < Runes.Count; i1++)
                {
                    Runes[i1] = atlas.WeaponRuneTable.RefLookup(Runes[i1].RawValue);
                }
            }
        }
    }

    #endregion
}
