// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/game.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class GameCfg
    {
        /// <summary>
        /// desc-x-int
        /// </summary>
        [JsonProperty("x-int")]
        public long XInt { get; set; }
        /// <summary>
        /// desc-x-int32
        /// </summary>
        [JsonProperty("x-int32")]
        public int XInt32 { get; set; }
        /// <summary>
        /// desc-x-float64
        /// </summary>
        [JsonProperty("x-float64")]
        public double XFloat64 { get; set; }
        /// <summary>
        /// desc-x-string
        /// </summary>
        [JsonProperty("x-string")]
        public string XString { get; set; } = null!;
        /// <summary>
        /// desc-x-bool
        /// </summary>
        [JsonProperty("x-bool")]
        public bool XBool { get; set; }
        /// <summary>
        /// desc-x-duration
        /// </summary>
        [JsonProperty("x-duration")]
        public Duration XDuration { get; set; }
        /// <summary>
        /// desc-x-path
        /// </summary>
        [JsonProperty("x-path")]
        public string XPath { get; set; } = null!;
        /// <summary>
        /// desc-x-datetime
        /// </summary>
        [JsonProperty("x-datetime")]
        public DateTimeOffset XDatetime { get; set; }
        /// <summary>
        /// desc-x-ref
        /// </summary>
        [JsonProperty("x-ref")]
        public XRef<long, WeaponRuneCfg> XRef { get; set; }
        /// <summary>
        /// desc-x-l10n
        /// </summary>
        [JsonProperty("x-l10n")]
        public L10n XL10n { get; set; }
        /// <summary>
        /// desc-x-array1
        /// </summary>
        [JsonProperty("x-array1")]
        public List<long>? XArray1 { get; set; }
        /// <summary>
        /// desc-x-array2
        /// </summary>
        [JsonProperty("x-array2")]
        public List<sbyte>? XArray2 { get; set; }
        /// <summary>
        /// desc-x-map
        /// </summary>
        [JsonProperty("x-map")]
        public Dictionary<long, string>? XMap { get; set; }
        /// <summary>
        /// desc-x-object
        /// </summary>
        [JsonProperty("x-object")]
        public Game_XObject? XObject { get; set; }
        /// <summary>
        /// desc-x-tuple
        /// </summary>
        [JsonProperty("x-tuple")]
        public Tup3<long, float, string>? XTuple { get; set; }
        /// <summary>
        /// desc-x-vector
        /// </summary>
        [JsonProperty("x-vector")]
        public Vec3<int> XVector { get; set; }
    }

    // Game_XObject represents $['x-object']
    public partial class Game_XObject
    {
        [JsonProperty("fieldX")]
        public long FieldX { get; set; }
        [JsonProperty("fieldY")]
        public string FieldY { get; set; } = null!;
    }

    #region Trifles

    public partial class GameCfg : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            XRef = atlas.WeaponRuneTable.RefLookup(XRef.RawValue);
        }
    }

    #endregion
}
