// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/game.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage;
using UnityEngine;

namespace Conf
{
    public partial class GameCfg
    {
        // desc-x-int
        [JsonProperty("x-int")]
        public long XInt { get; set; }
        // desc-x-int32
        [JsonProperty("x-int32")]
        public int XInt32 { get; set; }
        // desc-x-float64
        [JsonProperty("x-float64")]
        public double XFloat64 { get; set; }
        // desc-x-string
        [JsonProperty("x-string")]
        public string XString { get; set; } = string.Empty;
        // desc-x-bool
        [JsonProperty("x-bool")]
        public bool XBool { get; set; }
        // desc-x-duration
        [JsonProperty("x-duration")]
        public Duration XDuration { get; set; }
        // desc-x-path
        [JsonProperty("x-path")]
        public string XPath { get; set; } = string.Empty;
        // desc-x-datetime
        [JsonProperty("x-datetime")]
        public DateTimeOffset XDatetime { get; set; }
        // desc-x-ref
        [JsonProperty("x-ref")]
        public XRef<WeaponRuneCfgId, WeaponRuneCfg> XRef { get; set; }
        // desc-x-l10n
        [JsonProperty("x-l10n")]
        public L10n XL10n { get; set; }
        // desc-x-array1
        [JsonProperty("x-array1")]
        public List<long>? XArray1 { get; set; }
        // desc-x-array2
        [JsonProperty("x-array2")]
        public List<sbyte>? XArray2 { get; set; }
        // desc-x-map
        [JsonProperty("x-map")]
        public Dictionary<long, string>? XMap { get; set; }
        // desc-x-object
        [JsonProperty("x-object")]
        public Game_XObject? XObject { get; set; }
        // desc-x-tuple
        [JsonProperty("x-tuple")]
        public Tup3<long, float, string>? XTuple { get; set; }
        // desc-x-vector2
        [JsonProperty("x-vector2")]
        public Vector2Int XVector2 { get; set; }
        // desc-x-vector3
        [JsonProperty("x-vector3")]
        public Vector3 XVector3 { get; set; }
        // desc-x-vector4
        [JsonProperty("x-vector4")]
        public Vector4 XVector4 { get; set; }
        // desc-x-vector4x
        [JsonProperty("x-vector4x")]
        public Vec4<int> XVector4x { get; set; }
    }

    // Game_XObject represents $['x-object']
    public partial class Game_XObject
    {
        [JsonProperty("fieldX")]
        public long FieldX { get; set; }
        [JsonProperty("fieldY")]
        public string FieldY { get; set; } = string.Empty;
    }

    #region Trifles

    public partial class GameCfg : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            XRef = atlas.WeaponRuneTable.RefLookup(XRef.RawValue);
        }
    }

    #endregion
}
