// Code generated by (shadowopera) archmage. DO NOT EDIT.

#nullable enable

using System;
using Shadop.Archmage;
using Newtonsoft.Json;

namespace Conf
{
    [JsonConverter(typeof(L10nJsonConverter))]
    public readonly partial struct L10n
    {
        public static L10n Empty = new(string.Empty);

        // GetI18n must be set before calling L10n.GetText() and L10n.Text.
        public static Func<I18n>? GetI18n = null;
        // GetPreferredLanguge must be set before calling L10n.Text.
        public static Func<string>? GetPreferredLanguge = null;

        readonly string _key;

        public L10n(string key) { _key = key; }

        public bool GetText(string lang, out string? text) => GetI18n!().GetText(_key, lang, out text);
        public string Text => GetI18n!().Text(_key, GetPreferredLanguge!());

        public override string ToString() => _key;
    }

    public class L10nJsonConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType) => objectType == typeof(L10n);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.String)
                return new L10n((string)reader.Value!);
            if (reader.TokenType == JsonToken.Null)
                return L10n.Empty;
            throw new JsonSerializationException($"Expected string for L10n, got {reader.TokenType}");
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
        {
            var l10n = (L10n)value!;
            writer.WriteValue(l10n.ToString());
        }
    }
}
