// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Magic

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;

namespace Conf
{
    [Serializable]
    public partial struct MagicCfgId
    {
        public long Value;
        public MagicCfg Cfg => ConfigAtlas.Instance.MagicTable[Value]!;
    }

    public partial class MagicTable : Dictionary<MagicCfgId, MagicCfg> { }

    public partial class MagicCfg
    {
        [JsonProperty("id")] public MagicCfgId Id { get; set; }
        [JsonProperty("name")] public string Name { get; set; } = string.Empty;
    }

    public partial class MagicTable
    {
        public bool TryLookup(MagicCfgId cfgId, out MagicCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this, "MagicTable", out cfg);
        }

        public MagicCfg? Lookup(MagicCfgId cfgId)
        {
            return ConfigAtlas.Lookup(cfgId, this, "MagicTable");
        }

        internal XRef<MagicCfgId, MagicCfg> RefLookup(MagicCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup(cfgId, this, "MagicTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(MagicCfgIdJsonConverter))]
    [TypeConverter(typeof(MagicCfgIdTypeConverter))]
    public partial struct MagicCfgId : IEquatable<MagicCfgId>, IZero
    {
        public MagicCfgId(long value) { Value = value; }
        public static implicit operator MagicCfgId(long value) => new() { Value = value };
        public static implicit operator long(MagicCfgId obj) => obj.Value;

        public bool Equals(MagicCfgId other) => Value == other.Value;
        public override bool Equals(object? obj) => obj is MagicCfgId other && Equals(other);
        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(MagicCfgId left, MagicCfgId right) => left.Value == right.Value;
        public static bool operator !=(MagicCfgId left, MagicCfgId right) => left.Value != right.Value;

        public override string ToString() => Value.ToString();
        public bool IsZero => Value == 0;
    }

    internal class MagicCfgIdJsonConverter : ValueWrapperJsonConverter<MagicCfgId, long>
    {
        protected override MagicCfgId Create(long value) => value;
        protected override long GetValue(MagicCfgId obj) => obj.Value;
    }

    internal class MagicCfgIdTypeConverter : ValueWrapperTypeConverter<MagicCfgId, long>
    {
        protected override MagicCfgId Create(long value) => value;
    }

    public partial class MagicTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val is not null) val.Id = key;
            }
        }
    }

    #endregion
}
