// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/matrix2.js

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class Matrix2Table : Dictionary<string, Dictionary<string, List<List<XRef<HeroCfgId, HeroCfg>>>>?> {}

    #region Trifles

    public partial class Matrix2Table : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                if (v1 == null) continue;
                foreach (var v2 in v1.Values)
                {
                    if (v2 == null) continue;
                    foreach (var v3 in v2)
                    {
                        if (v3 == null) continue;
                        for (var i4 = 0; i4 < v3.Count; i4++)
                        {
                            v3[i4] = atlas.HeroTable.RefLookup(v3[i4].CfgId);
                        }
                    }
                }
            }
        }
    }

    #endregion
}
