// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/prop_floats.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class PropFloatsCfg
    {
        /// <summary>desc-B</summary>
        [JsonProperty("B")]
        public double B { get; set; }
        /// <summary>desc-C</summary>
        [JsonProperty("C")]
        public float C { get; set; }
        /// <summary>desc-D</summary>
        [JsonProperty("D")]
        public double D { get; set; }
        /// <summary>desc-E</summary>
        [JsonProperty("E")]
        public float E { get; set; }
        /// <summary>desc-F</summary>
        [JsonProperty("F")]
        public double F { get; set; }
        /// <summary>desc-G</summary>
        [JsonProperty("G")]
        public double G { get; set; }
    }

    #region Trifles

    #endregion
}
