// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/world.xlsx::Race

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;

namespace Conf
{
    [Serializable]
    public partial struct RaceCfgId
    {
        public string Value;
        public readonly RaceCfg Cfg => ConfigAtlas.Instance.RaceTable[Value]!;
    }

    public partial class RaceTable : Dictionary<RaceCfgId, RaceCfg> { }

    public partial class RaceCfg
    {
        [JsonProperty("id")] public RaceCfgId Id { get; set; } = string.Empty;
        /// <summary>Birthplace</summary>
        [JsonProperty("birthplace")] public L10n Birthplace { get; set; }
        /// <summary>Heroes</summary>
        [JsonProperty("heroes")] public List<XRef<HeroCfgId, HeroCfg>>? Heroes { get; set; }
        /// <summary>Hero IDs</summary>
        [JsonProperty("heroIds")] public List<long>? HeroIds { get; set; }
    }

    public partial class RaceTable
    {
        public bool TryLookup(RaceCfgId cfgId, [NotNullWhen(true)] out RaceCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this, "RaceTable", out cfg);
        }

        public RaceCfg? Lookup(RaceCfgId cfgId)
        {
            return ConfigAtlas.Lookup(cfgId, this, "RaceTable");
        }

        internal XRef<RaceCfgId, RaceCfg> RefLookup(RaceCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup(cfgId, this, "RaceTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(RaceCfgIdJsonConverter))]
    [TypeConverter(typeof(RaceCfgIdTypeConverter))]
    public partial struct RaceCfgId : IEquatable<RaceCfgId>, IZero
    {
        public RaceCfgId(string value) { Value = value; }
        public static implicit operator RaceCfgId(string value) => new() { Value = value };
        public static implicit operator string(RaceCfgId obj) => obj.Value ?? string.Empty;

        [Unity.Burst.BurstDiscard]
        public override readonly bool Equals(object? obj) => obj is RaceCfgId other && Equals(other);
        public readonly bool Equals(RaceCfgId other) => (Value ?? string.Empty) == (other.Value ?? string.Empty);
        public override readonly int GetHashCode() => (Value ?? string.Empty).GetHashCode();

        public static bool operator ==(RaceCfgId left, RaceCfgId right) => left.Equals(right);
        public static bool operator !=(RaceCfgId left, RaceCfgId right) => !left.Equals(right);

        public override readonly string ToString() => Value ?? string.Empty;
        public bool IsZero => string.IsNullOrEmpty(Value);
    }

    class RaceCfgIdJsonConverter : ValueWrapperJsonConverter<RaceCfgId, string>
    {
        protected override RaceCfgId Create(string value) => value;
        protected override string GetValue(RaceCfgId obj) => obj.Value ?? string.Empty;
    }

    class RaceCfgIdTypeConverter : ValueWrapperTypeConverter<RaceCfgId, string>
    {
        protected override RaceCfgId Create(string value) => value;
    }

    public partial class RaceTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val is not null) val.Id = key;
            }
        }
    }

    public partial class RaceTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                v1?.BindRefs(atlas);
            }
        }
    }

    public partial class RaceCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            if (Heroes is not null)
            {
                for (var i = 0; i < Heroes.Count; i++)
                {
                    Heroes[i] = atlas.HeroTable.RefLookup(Heroes[i].CfgId);
                }
            }
        }
    }

    #endregion
}
