// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/ref.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class RefTable : Dictionary<long, RefCfg?>
    {
        // Definition only.
    }

    public partial class RefCfg
    {
        [JsonIgnore]
        public long Id { get; set; }
        /// <summary>
        /// desc-B
        /// </summary>
        [JsonProperty("B")]
        public XRef<long, WeaponRuneCfg> B { get; set; }
        /// <summary>
        /// desc-C
        /// </summary>
        [JsonProperty("C")]
        public long C { get; set; }
        /// <summary>
        /// desc-D
        /// </summary>
        [JsonProperty("D")]
        public XRef<long, ItemCfg> D { get; set; }
        /// <summary>
        /// desc-E
        /// </summary>
        [JsonProperty("E")]
        public XRef<long, MagicCfg> E { get; set; }
        /// <summary>
        /// desc-F
        /// </summary>
        [JsonProperty("F")]
        public XRef<string, RaceCfg> F { get; set; }
        /// <summary>
        /// desc-G
        /// </summary>
        [JsonProperty("G")]
        public XRef<long, HeroCfg> G { get; set; }
        /// <summary>
        /// desc-H
        /// </summary>
        [JsonProperty("H")]
        public List<XRef<string, StringCfg>>? H { get; set; }
        /// <summary>
        /// desc-J
        /// </summary>
        [JsonProperty("J")]
        public XRef<long, ItemCfg> J { get; set; }
        /// <summary>
        /// desc-K
        /// </summary>
        [JsonProperty("K")]
        public XRef<string, RaceCfg> K { get; set; }
    }

    public partial class RefTable
    {
        public bool TryLookup(long cfgID, out RefCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgID, this!, "RefTable", out cfg);
        }

        public RefCfg? Lookup(long cfgID)
        {
            return ConfigAtlas.Lookup<long, RefCfg>(cfgID, this!, "RefTable");
        }

        internal XRef<long, RefCfg> RefLookup(long cfgID)
        {
            return ConfigAtlas.MakeXRef(cfgID, ConfigAtlas.Lookup<long, RefCfg>(cfgID, this!, "RefTable"));
        }
    }

    #region Trifles

    public partial class RefTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    public partial class RefTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                if (v1 != null)
                    v1.BindRefs(atlas);
            }
        }
    }

    public partial class RefCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            B = atlas.WeaponRuneTable.RefLookup(B.RawValue);
            D = atlas.ItemTable.RefLookup(D.RawValue);
            E = atlas.MagicTable.RefLookup(E.RawValue);
            F = atlas.RaceTable.RefLookup(F.RawValue);
            G = atlas.HeroTable.RefLookup(G.RawValue);
            if (H != null)
            {
                for (var i1 = 0; i1 < H.Count; i1++)
                {
                    H[i1] = atlas.StringTable.RefLookup(H[i1].RawValue);
                }
            }
            J = atlas.ItemTable.RefLookup(J.RawValue);
            K = atlas.RaceTable.RefLookup(K.RawValue);
        }
    }

    #endregion
}
