// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtSkill (virtual table)

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;

namespace Conf
{
    [Serializable]
    public partial struct VtSkillCfgId
    {
        public string Value;
        public VtSkillCfg Cfg => ConfigAtlas.Instance.VtSkillTable[Value]!;
    }

    public partial class VtSkillTable : Dictionary<VtSkillCfgId, VtSkillCfg> { }

    public partial class VtSkillCfg
    {
        [JsonProperty("id")] public VtSkillCfgId Id { get; set; } = string.Empty;
        [JsonProperty("name")] public string Name { get; set; } = string.Empty;
        [JsonProperty("class")] public string Class { get; set; } = string.Empty;
        [JsonProperty("Foo")] public Dictionary<long, VtSkill_FooEntry>? Foo { get; set; }
        /// <summary>reagent</summary>
        [JsonProperty("reagent")] public long Reagent { get; set; }
        [JsonProperty("cross-skill1")] public string CrossSkill1 { get; set; } = string.Empty;
        [JsonProperty("weapons")] public List<long>? Weapons { get; set; }
        [JsonProperty("cross-skill2")] public string CrossSkill2 { get; set; } = string.Empty;
    }

    // VtSkill_FooEntry represents $.*.Foo.*
    public partial class VtSkill_FooEntry
    {
        /// <summary>X1a</summary>
        [JsonProperty("X1")] public string X1 { get; set; } = string.Empty;
        [JsonProperty("X2")] public Duration X2 { get; set; }
        /// <summary>X5</summary>
        [JsonProperty("X5")] public long X5 { get; set; }
    }

    public partial class VtSkillTable
    {
        public bool TryLookup(VtSkillCfgId cfgId, out VtSkillCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this, "VtSkillTable", out cfg);
        }

        public VtSkillCfg? Lookup(VtSkillCfgId cfgId)
        {
            return ConfigAtlas.Lookup(cfgId, this, "VtSkillTable");
        }

        internal XRef<VtSkillCfgId, VtSkillCfg> RefLookup(VtSkillCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup(cfgId, this, "VtSkillTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(VtSkillCfgIdJsonConverter))]
    [TypeConverter(typeof(VtSkillCfgIdTypeConverter))]
    public partial struct VtSkillCfgId : IEquatable<VtSkillCfgId>, IZero
    {
        public VtSkillCfgId(string value) { Value = value; }
        public static implicit operator VtSkillCfgId(string value) => new() { Value = value };
        public static implicit operator string(VtSkillCfgId obj) => obj.Value;

        [Unity.Burst.BurstDiscard]
        public override bool Equals(object? obj) => obj is VtSkillCfgId other && Equals(other);
        public bool Equals(VtSkillCfgId other) => Value == other.Value;
        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(VtSkillCfgId left, VtSkillCfgId right) => left.Value == right.Value;
        public static bool operator !=(VtSkillCfgId left, VtSkillCfgId right) => left.Value != right.Value;

        public override string ToString() => Value;
        public bool IsZero => string.IsNullOrEmpty(Value);
    }

    internal class VtSkillCfgIdJsonConverter : ValueWrapperJsonConverter<VtSkillCfgId, string>
    {
        protected override VtSkillCfgId Create(string value) => value;
        protected override string GetValue(VtSkillCfgId obj) => obj.Value;
    }

    internal class VtSkillCfgIdTypeConverter : ValueWrapperTypeConverter<VtSkillCfgId, string>
    {
        protected override VtSkillCfgId Create(string value) => value;
    }

    public partial class VtSkillTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val is not null) val.Id = key;
            }
        }
    }

    #endregion
}
