// This file was initially generated by (shadop.dev) archmage.
// Feel free to edit this file as it will not be overwritten in subsequent runs.

#if TOOLS

#nullable enable

using System;
using Godot;
using Shadop.Archmage.Sdk;

namespace Conf.Editor
{
    [Tool]
    public partial class ArchmageEditorPlugin : EditorPlugin
    {
        const string ReloadMenuItem = "Reload Game Configs for Editor";

        static bool _loaded;

        CfgIdInspectorPlugin? _inspectorPlugin;

        public override void _EnterTree()
        {
            _inspectorPlugin = new CfgIdInspectorPlugin();
            AddInspectorPlugin(_inspectorPlugin);
            AddToolMenuItem(ReloadMenuItem, Callable.From(ReloadGameConfigs));
        }

        public override void _ExitTree()
        {
            RemoveToolMenuItem(ReloadMenuItem);
            if (_inspectorPlugin != null)
            {
                RemoveInspectorPlugin(_inspectorPlugin);
                _inspectorPlugin = null;
            }
        }

        // After a build, the editor reloads the C# assemblies, which clears the static fields, and does not call
        // _EnterTree again. So the configs are loaded when the Inspector first needs them.
        public static void EnsureGameConfigsLoaded()
        {
            if (!_loaded)
                ReloadGameConfigs();
        }

        static void ReloadGameConfigs()
        {
            _loaded = true;
            TypeDescriptorCleanup.Install();
            try
            {
                LoadGameConfigs();

                var atlas = ConfigAtlas.Instance;
                if (atlas == null!)
                {
                    GD.PushWarning("<archmage> Failed to load game configs for the editor: ConfigAtlas.Instance is null.");
                    return;
                }

                InitializeCfgIdChoices(atlas);

                // Rebuilds the property editors of the object shown in the Inspector.
                EditorInterface.Singleton.GetInspector().GetEditedObject()?.NotifyPropertyListChanged();
                GD.Print("<archmage> Game configs loaded for the editor.");
            }
            catch (Exception ex)
            {
                GD.PushError($"<archmage> Failed to load game configs for the editor: {ex}");
            }
        }

        static void LoadGameConfigs()
        {
            const string cfgRoot = "res://configs";
            var fs = new GodotFileAccessFS();
            var atlas = new ConfigAtlas();
            var options = new AtlasOptions()
                .WithLogger(new GodotAtlasLogger())
                .WithJsonSettings(GodotJsonSettingsFactory.Create())
                .WithFS(fs)
                .WithVariant("balance", "hard");
            Archmage.LoadAtlas($"{cfgRoot}/atlas.json", cfgRoot, atlas, options);

            var i18n = new I18n("en");
            i18n.MergeL10nFile($"{cfgRoot}/l10n.json", "en", fs);
            L10n.GetI18n = () => i18n;
            L10n.GetPreferredLanguage = () => "en";
            ConfigAtlas.Instance = atlas;
        }

        static void InitializeCfgIdChoices(ConfigAtlas atlas)
        {
            // Initialize XxxCfgIdChoices on demand
            HeroCfgIdChoices.Register(atlas.HeroTable, v => $"{v} ({new HeroCfgId(v).Cfg.Name.Text})");
            RaceCfgIdChoices.Register(atlas.RaceTable, v => $"{v} ({new RaceCfgId { Value = v }.Cfg.Birthplace.Text})");
        }
    }
}

#endif
