// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.

#if TOOLS

#nullable enable

using Godot;

namespace Conf.Editor
{
    [Tool]
    public partial class CfgIdInspectorPlugin : EditorInspectorPlugin
    {
        public override bool _CanHandle(GodotObject @object)
        {
            ArchmageEditorPlugin.EnsureGameConfigsLoaded();
            return true;
        }

        public override bool _ParseProperty(GodotObject @object, Variant.Type type, string name, PropertyHint hintType,
            string hintString, PropertyUsageFlags usageFlags, bool wide)
        {
            if (hintType != PropertyHint.None || !CfgIdChoices.TryGet(hintString, out var choices) || type != choices.Type)
                return false;
            AddPropertyEditor(name, new CfgIdEditorProperty(hintString));
            return true;
        }
    }
}

#endif
