// Code generated by (shadop.dev) archmage. DO NOT EDIT.

#if TOOLS

#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace Conf.Editor
{
    /// <summary>
    /// The IDs of one config table, with their display names, for the dropdown of a config ID property.
    /// A property uses them when its hint string is the key they are registered with, such as
    /// <c>[Export(PropertyHint.None, "HeroCfgId")] public long Hero { get; set; }</c>.
    /// </summary>
    public sealed class CfgIdChoices
    {
        static readonly Dictionary<string, CfgIdChoices> Registry = new();

        public Variant.Type Type { get; }
        public Variant[] Values { get; }
        public string[] Names { get; }

        CfgIdChoices(Variant.Type type, Variant[] values, string[] names)
        {
            Type = type;
            Values = values;
            Names = names;
        }

        public static bool TryGet(string key, [NotNullWhen(true)] out CfgIdChoices? choices) =>
            Registry.TryGetValue(key, out choices);

        public static void RegisterInt<TId, [MustBeVariant] TValue>(string key, ICollection<TId> ids, Func<TId, TValue> id2Value, Func<TValue, string> format)
            where TValue : unmanaged, IComparable<TValue>
        {
            var values = new TValue[ids.Count + 1];
            var i = 1;
            foreach (var id in ids)
                values[i++] = id2Value(id);
            Array.Sort(values, 1, ids.Count);

            var variants = new Variant[values.Length];
            var names = new string[values.Length];
            names[0] = "0 (Default)";
            for (i = 0; i < values.Length; i++)
            {
                variants[i] = Variant.From(values[i]);
                if (i > 0)
                    names[i] = format(values[i]);
            }
            Registry[key] = new CfgIdChoices(Variant.Type.Int, variants, names);
        }

        public static void RegisterStr<TId>(string key, ICollection<TId> ids, Func<TId, string> id2Value, Func<string, string> format)
        {
            var values = new string[ids.Count + 1];
            values[0] = string.Empty;
            var i = 1;
            foreach (var id in ids)
                values[i++] = id2Value(id);
            Array.Sort(values, 1, ids.Count, StringComparer.Ordinal);

            var variants = new Variant[values.Length];
            var names = new string[values.Length];
            names[0] = "\"\" (Default)";
            for (i = 0; i < values.Length; i++)
            {
                variants[i] = values[i];
                if (i > 0)
                    names[i] = format(values[i]);
            }
            Registry[key] = new CfgIdChoices(Variant.Type.String, variants, names);
        }
    }
}

#endif
