// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.

#if TOOLS

#nullable enable

using Godot;

namespace Conf.Editor
{
    [Tool]
    public partial class CfgIdEditorProperty : EditorProperty
    {
        readonly OptionButton _button = new();
        string _key = string.Empty;

        // Godot needs a parameterless constructor to recreate the object after the C# assembly is reloaded.
        public CfgIdEditorProperty()
        {
            _button.ClipText = true;
            _button.ItemSelected += OnItemSelected;
            AddChild(_button);
            AddFocusable(_button);
        }

        public CfgIdEditorProperty(string key) : this()
        {
            _key = key;
        }

        public override void _UpdateProperty()
        {
            _button.Clear();
            if (!CfgIdChoices.TryGet(_key, out var choices))
                return;

            var value = GetEditedObject().Get(GetEditedProperty());
            var selected = -1;
            for (var i = 0; i < choices.Names.Length; i++)
            {
                _button.AddItem(choices.Names[i], i);
                if (Equals(choices.Values[i].Obj, value.Obj))
                    selected = i;
            }
            if (selected < 0)
            {
                // The value is not in the table; show it so that it is not silently replaced.
                selected = _button.ItemCount;
                _button.AddItem($"{value} (Missing)", selected);
            }
            _button.Select(selected);
        }

        void OnItemSelected(long index)
        {
            if (!CfgIdChoices.TryGet(_key, out var choices) || index >= choices.Values.Length)
                return;
            EmitChanged(GetEditedProperty(), choices.Values[index]);
        }
    }
}

#endif
