// Code generated by (shadop.dev) archmage. DO NOT EDIT.

#if TOOLS

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;

namespace Conf.Editor
{
    // After a build, the editor unloads the collectible AssemblyLoadContext of the game assembly and loads the new
    // build. The unload fails ("Failed to unload assemblies") while the static caches of TypeDescriptor hold types of
    // that context. Newtonsoft.Json asks TypeDescriptor about every type that it deserializes, and the generated
    // ConfigAtlas adds a TypeDescriptor provider for each CfgId type. This removes the collectible types from the caches
    // when the context unloads. The caches are private fields of .NET; if a .NET version renames them, the reload fails
    // as before.
    static class TypeDescriptorCleanup
    {
        const BindingFlags StaticFlags = BindingFlags.Static | BindingFlags.NonPublic;
        const BindingFlags InstanceFlags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;

        static bool _installed;

        // Call it before the editor code deserializes anything. It takes effect once for each load of the assembly.
        public static void Install()
        {
            if (_installed)
                return;
            _installed = true;
            var alc = AssemblyLoadContext.GetLoadContext(typeof(TypeDescriptorCleanup).Assembly);
            if (alc is { IsCollectible: true })
                alc.Unloading += _ => RemoveCollectibleTypes();
        }

        static void RemoveCollectibleTypes()
        {
            var descriptor = typeof(TypeDescriptor);
            var reflectProvider = descriptor.Assembly.GetType("System.ComponentModel.ReflectTypeDescriptionProvider");
            var providerTable = descriptor.GetField("s_providerTable", StaticFlags)?.GetValue(null) as Hashtable;

            // _typeData is an instance field of the ReflectTypeDescriptionProvider objects at the end of the provider
            // chains in s_providerTable, so find them before s_providerTable is cleaned.
            var typeDataTables = new List<object?>();
            if (providerTable != null && reflectProvider != null)
            {
                lock (providerTable)
                {
                    var providers = new HashSet<object>();
                    foreach (DictionaryEntry entry in providerTable)
                    {
                        for (var node = entry.Value; node != null; node = node.GetType().GetField("Next", InstanceFlags)?.GetValue(node))
                        {
                            var provider = node.GetType().GetField("Provider", InstanceFlags)?.GetValue(node);
                            if (provider != null && reflectProvider.IsInstanceOfType(provider) && providers.Add(provider))
                                typeDataTables.Add(reflectProvider.GetField("_typeData", InstanceFlags)?.GetValue(provider));
                        }
                    }
                }
            }

            Remove(providerTable);
            Remove(descriptor.GetField("s_providerTypeTable", StaticFlags)?.GetValue(null));
            Remove(descriptor.GetField("s_defaultProviderInitialized", StaticFlags)?.GetValue(null));
            if (reflectProvider != null)
            {
                foreach (var name in new[] { "s_attributeCache", "s_propertyCache", "s_eventCache", "s_extendedPropertyCache" })
                    Remove(reflectProvider.GetField(name, StaticFlags)?.GetValue(null));
            }
            foreach (var table in typeDataTables)
                Remove(table);
        }

        // Type.IsCollectible is also true for a constructed type whose type arguments are collectible,
        // such as IEquatable<Vec2<int>>.
        static void Remove(object? table)
        {
            if (table is not IDictionary dict)
                return;
            lock (table)
            {
                foreach (var key in dict.Keys.Cast<object>().Where(k => k is Type { IsCollectible: true }).ToList())
                    dict.Remove(key);
            }
        }
    }
}

#endif
