// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.

#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Shadop.Archmage.Sdk;

namespace Conf
{
    /// <summary>
    /// Holds all game configuration tables and provides cross-table reference binding.
    /// </summary>
    public partial class ConfigAtlas : IAtlas
    {
        /// <summary>
        /// The active ConfigAtlas. It must be set before calling any XxxCfgId.Cfg.
        /// </summary>
        public static ConfigAtlas Instance = null!;

        /// <summary>
        /// The user-defined configuration extensions.
        /// </summary>
        public AtlasExtension Extension { get; private set; }
        /// <summary>
        /// The version info of the config repo at export time.
        /// </summary>
        public VersionInfo? DataVersion { get; private set; }

        public BalanceCfg BalanceCfg { get; set; }
        public ChapterArray ChapterArray { get; set; }
        public DropTable DropTable { get; set; }
        public GameCfg GameCfg { get; set; }
        public HeroTable HeroTable { get; set; }
        public ItemTable ItemTable { get; set; }
        public MonsterTable MonsterTable { get; set; }
        public RaceTable RaceTable { get; set; }
        public RegionTable RegionTable { get; set; }
        public RouteTable RouteTable { get; set; }
        public SkillTable SkillTable { get; set; }

        Dictionary<string, AtlasItem> _m = null!;

        public ConfigAtlas()
        {
            PubtypeCheck();
            Extension = new AtlasExtension();
            BalanceCfg = new BalanceCfg();
            ChapterArray = new ChapterArray();
            DropTable = new DropTable();
            GameCfg = new GameCfg();
            HeroTable = new HeroTable();
            ItemTable = new ItemTable();
            MonsterTable = new MonsterTable();
            RaceTable = new RaceTable();
            RegionTable = new RegionTable();
            RouteTable = new RouteTable();
            SkillTable = new SkillTable();
            BuildMap();
        }

        void BuildMap()
        {
            _m = new Dictionary<string, AtlasItem>
            {
                { "balance", new AtlasItem { Cfg = BalanceCfg, Mapping = "variant" } },
                { "chapter", new AtlasItem { Cfg = ChapterArray, Mapping = "unique" } },
                { "drop", new AtlasItem { Cfg = DropTable, Mapping = "unique" } },
                { "game", new AtlasItem { Cfg = GameCfg, Mapping = "variant" } },
                { "hero", new AtlasItem { Cfg = HeroTable, Mapping = "unique" } },
                { "item", new AtlasItem { Cfg = ItemTable, Mapping = "unique" } },
                { "monster", new AtlasItem { Cfg = MonsterTable, Mapping = "unique" } },
                { "Race", new AtlasItem { Cfg = RaceTable, Mapping = "unique" } },
                { "Region", new AtlasItem { Cfg = RegionTable, Mapping = "unique" } },
                { "route", new AtlasItem { Cfg = RouteTable, Mapping = "unique" } },
                { "skill", new AtlasItem { Cfg = SkillTable, Mapping = "many" } },
            };
        }

        /// <summary>For internal use only.</summary>
        public void SetDataVersion(VersionInfo? v)
        {
            DataVersion = v;
        }

        /// <summary>For internal use only.</summary>
        public void BindRefs()
        {
            var keys = new List<string>(_m.Keys);
            keys.Sort(StringComparer.OrdinalIgnoreCase);
            foreach (var k in keys)
            {
                if (_m[k].Cfg is IRefBinder binder)
                    binder.BindRefs(this);
            }
        }

        /// <summary>
        /// Returns the internal map of config-name to AtlasItem.
        /// </summary>
        public Dictionary<string, AtlasItem> AtlasItems()
        {
            return _m;
        }

        /// <summary>
        /// Called after all config data has been loaded and refs bound. Delegates to
        /// AtlasExtension.OnLoaded. For internal use only.
        /// </summary>
        public void OnLoaded()
        {
            Extension.OnLoaded(this);
        }

        internal static XRef<V, T> MakeXRef<V, T>(V cfgId, T? refValue)
            where V : notnull
            where T : class
            => new(cfgId, refValue);

        internal static bool TryLookup<K, V>(K cfgId, Dictionary<K, V> tbl, string tblName, [NotNullWhen(true)] out V? cfg)
            where K : notnull
            where V : class
        {
            return tbl.TryGetValue(cfgId, out cfg);
        }

        internal static V? Lookup<K, V>(K cfgId, Dictionary<K, V> tbl, string tblName)
            where K : notnull
            where V : class
        {
            if (cfgId is IZero z && z.IsZero)
                return null;
            if (tbl.TryGetValue(cfgId, out var cfg))
                return cfg;
            throw new KeyNotFoundException($"{tblName}: config entry not found for Id {cfgId}");
        }

        static void PubtypeCheck()
        {
            var m = new HashSet<string>();
            m.Add("Stats"); // hero
            m.Add("Price"); // item
            if (m.Count != 2)
                throw new Exception("conflicting pubtype detected");
        }
    }

    interface IRefBinder
    {
        void BindRefs(ConfigAtlas atlas);
    }
}
