// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/character.json5

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;

namespace Conf
{
    public partial class CharacterArray : List<CharacterCfg?> { }

    public partial class CharacterCfg
    {
        [JsonProperty("id")] public string Id { get; set; } = string.Empty;
        /// <summary>name config</summary>
        [JsonProperty("name")] public L10n Name { get; set; }
        /// <summary>race config</summary>
        [JsonProperty("race")] public XRef<RaceCfgId, RaceCfg> Race { get; set; }
        [JsonProperty("root")] public Vec3<long> Root { get; set; }
        /// <summary>health config</summary>
        [JsonProperty("health")] public long Health { get; set; }
        [JsonProperty("attack")] public double Attack { get; set; }
        [JsonProperty("isPlayable")] public bool IsPlayable { get; set; }
        [JsonProperty("skills")] public List<string>? Skills { get; set; }
        /// <summary>my runes</summary>
        [JsonProperty("runes")] public List<XRef<WeaponRuneCfgId, WeaponRuneCfg>>? Runes { get; set; }
        [JsonProperty("ultimateSkill")] public string UltimateSkill { get; set; } = string.Empty;
        [JsonProperty("ref-crude")] public Character_RefCrude? RefCrude { get; set; }
    }

    // Character_RefCrude represents $.*['ref-crude']
    public partial class Character_RefCrude
    {
        [JsonProperty("r1")] public long R1 { get; set; }
        [JsonProperty("r2")] public string R2 { get; set; } = string.Empty;
    }

    #region Trifles

    public partial class CharacterArray : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this)
            {
                if (v1 is not null)
                    v1.BindRefs(atlas);
            }
        }
    }

    public partial class CharacterCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Race = atlas.RaceTable.RefLookup(Race.CfgId);
            if (Runes is not null)
            {
                for (var i1 = 0; i1 < Runes.Count; i1++)
                {
                    Runes[i1] = atlas.WeaponRuneTable.RefLookup(Runes[i1].CfgId);
                }
            }
        }
    }

    #endregion
}
