// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/game.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;
using Conf.Enums;

namespace Conf
{
    public partial class GameCfg
    {
        /// <summary>Game title</summary>
        [JsonProperty("title")] public L10n Title { get; set; }
        /// <summary>Max level</summary>
        [JsonProperty("maxLevel")] public int MaxLevel { get; set; }
        /// <summary>Starting hero</summary>
        [JsonProperty("startHero")] public XRef<HeroCfgId, HeroCfg> StartHero { get; set; }
        /// <summary>Server tick</summary>
        [JsonProperty("tickRate")] public Duration TickRate { get; set; }
        /// <summary>Background color</summary>
        [JsonProperty("bgColor")] public Rgba BgColor { get; set; }
        /// <summary>Launch date</summary>
        [JsonProperty("launchDate")] public DateTimeOffset LaunchDate { get; set; }
        /// <summary>Theme music</summary>
        [JsonProperty("bgm")] public string Bgm { get; set; } = string.Empty;
        /// <summary>Starter items</summary>
        [JsonProperty("starterItems")] public List<XRef<ItemCfgId, ItemCfg>>? StarterItems { get; set; }
        /// <summary>Daily resets</summary>
        [JsonProperty("dailyResets")] public List<Duration>? DailyResets { get; set; }
        /// <summary>Allowed classes</summary>
        [JsonProperty("allowedClasses")] public List<HeroClass>? AllowedClasses { get; set; }
        /// <summary>Level caps</summary>
        [JsonProperty("levelCaps")] public List<long>? LevelCaps { get; set; }
        /// <summary>Banned words</summary>
        [JsonProperty("bannedWords")] public List<string>? BannedWords { get; set; }
        /// <summary>Bag slot sizes</summary>
        [JsonProperty("slotSizes")] public List<sbyte>? SlotSizes { get; set; }
        /// <summary>Level rewards</summary>
        [JsonProperty("levelRewards")] public Dictionary<long, XRef<ItemCfgId, ItemCfg>>? LevelRewards { get; set; }
        /// <summary>Tips</summary>
        [JsonProperty("tips")] public Dictionary<string, L10n>? Tips { get; set; }
        /// <summary>Class colors</summary>
        [JsonProperty("classColors")] public Dictionary<HeroClass, Rgba>? ClassColors { get; set; }
        /// <summary>Features</summary>
        [JsonProperty("features")] public Dictionary<string, bool>? Features { get; set; }
        /// <summary>Message of the day</summary>
        [JsonProperty("motd")] public Tup1<string>? Motd { get; set; }
        /// <summary>Boss spawn</summary>
        [JsonProperty("bossSpawn")] public Tup7<XRef<HeroCfgId, HeroCfg>, HeroClass, Duration, short, float, bool, string>? BossSpawn { get; set; }
        /// <summary>Camera offset</summary>
        [JsonProperty("cameraOffset")] public Vec3<float> CameraOffset { get; set; }
        /// <summary>Grid size</summary>
        [JsonProperty("gridSize")] public Vec2<int> GridSize { get; set; }
        /// <summary>Tint</summary>
        [JsonProperty("tint")] public Vec4<float> Tint { get; set; }
        /// <summary>World bounds</summary>
        [JsonProperty("worldBounds")] public Vec4<int> WorldBounds { get; set; }
    }

    #region Trifles

    public partial class GameCfg : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            StartHero = atlas.HeroTable.RefLookup(StartHero.CfgId);
            if (StarterItems is not null)
            {
                for (var i1 = 0; i1 < StarterItems.Count; i1++)
                {
                    StarterItems[i1] = atlas.ItemTable.RefLookup(StarterItems[i1].CfgId);
                }
            }
            if (LevelRewards is not null)
            {
                foreach (var k1 in new List<long>(LevelRewards.Keys))
                {
                    LevelRewards[k1] = atlas.ItemTable.RefLookup(LevelRewards[k1].CfgId);
                }
            }
            if (BossSpawn is not null)
            {
                BossSpawn.Item0 = atlas.HeroTable.RefLookup(BossSpawn.Item0.CfgId);
            }
        }
    }

    #endregion
}
