// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/hero.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial struct HeroCfgId
    {
        public long Value { get; internal set; }
    }

    public partial class HeroTable : Dictionary<HeroCfgId, HeroCfg> {}

    public partial class HeroCfg
    {
        [JsonProperty("id")]
        public HeroCfgId Id { get; set; }
        [JsonProperty("heroName")]
        public L10n HeroName { get; set; }
        [JsonProperty("startLevel")]
        public long StartLevel { get; set; }
        [JsonProperty("referrer")]
        public List<XRef<RefCfgId, RefCfg>>? Referrer { get; set; }
        [JsonProperty("race-combo")]
        public List<Hero_RaceComboEntry>? RaceCombo { get; set; }
        [JsonProperty("referrer-sort")]
        public List<XRef<RefCfgId, RefCfg>>? ReferrerSort { get; set; }
        [JsonProperty("referrer-compact")]
        public List<XRef<RefCfgId, RefCfg>>? ReferrerCompact { get; set; }
        [JsonProperty("referrer-sort-compact")]
        public List<XRef<RefCfgId, RefCfg>>? ReferrerSortCompact { get; set; }
    }

    // Hero_RaceComboEntry represents $.*['race-combo'].*
    public partial class Hero_RaceComboEntry
    {
        [JsonProperty("race1")]
        public XRef<RaceCfgId, RaceCfg> Race1 { get; set; }
        [JsonProperty("race2")]
        public XRef<RaceCfgId, RaceCfg> Race2 { get; set; }
    }

    public partial class HeroTable
    {
        public bool TryLookup(HeroCfgId cfgId, out HeroCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this!, "HeroTable", out cfg);
        }

        public HeroCfg? Lookup(HeroCfgId cfgId)
        {
            return ConfigAtlas.Lookup<HeroCfgId, HeroCfg>(cfgId, this!, "HeroTable");
        }

        internal XRef<HeroCfgId, HeroCfg> RefLookup(HeroCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup<HeroCfgId, HeroCfg>(cfgId, this!, "HeroTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(HeroCfgIdJsonConverter))]
    [TypeConverter(typeof(HeroCfgIdTypeConverter))]
    public partial struct HeroCfgId : IEquatable<HeroCfgId>, IZero
    {
        public static implicit operator HeroCfgId(long value) => new() { Value = value };
        public static implicit operator long(HeroCfgId obj) => obj.Value;

        public bool Equals(HeroCfgId other) => Value == other.Value;
        public override bool Equals(object? obj) => obj is HeroCfgId other && Equals(other);
        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(HeroCfgId left, HeroCfgId right) => left.Value == right.Value;
        public static bool operator !=(HeroCfgId left, HeroCfgId right) => left.Value != right.Value;

        public override string ToString() => Value.ToString();
        public bool IsZero => Value == default;
    }

    internal class HeroCfgIdJsonConverter : ValueWrapperJsonConverter<HeroCfgId, long>
    {
        protected override HeroCfgId Create(long value) => value;
        protected override long GetValue(HeroCfgId obj) => obj.Value;
    }

    internal class HeroCfgIdTypeConverter : ValueWrapperTypeConverter<HeroCfgId, long>
    {
        protected override HeroCfgId Create(long value) => value;
    }

    public partial class HeroTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    public partial class HeroTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                if (v1 != null)
                    v1.BindRefs(atlas);
            }
        }
    }

    public partial class HeroCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            if (Referrer != null)
            {
                for (var i = 0; i < Referrer.Count; i++)
                {
                    Referrer[i] = atlas.RefTable.RefLookup(Referrer[i].CfgId);
                }
            }
            if (RaceCombo != null)
            {
                foreach (var v1 in RaceCombo)
                {
                    if (v1 != null)
                        v1.BindRefs(atlas);
                }
            }
            if (ReferrerSort != null)
            {
                for (var i = 0; i < ReferrerSort.Count; i++)
                {
                    ReferrerSort[i] = atlas.RefTable.RefLookup(ReferrerSort[i].CfgId);
                }
            }
            if (ReferrerCompact != null)
            {
                for (var i = 0; i < ReferrerCompact.Count; i++)
                {
                    ReferrerCompact[i] = atlas.RefTable.RefLookup(ReferrerCompact[i].CfgId);
                }
            }
            if (ReferrerSortCompact != null)
            {
                for (var i = 0; i < ReferrerSortCompact.Count; i++)
                {
                    ReferrerSortCompact[i] = atlas.RefTable.RefLookup(ReferrerSortCompact[i].CfgId);
                }
            }
        }
    }

    public partial class Hero_RaceComboEntry
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Race1 = atlas.RaceTable.RefLookup(Race1.CfgId);
            Race2 = atlas.RaceTable.RefLookup(Race2.CfgId);
        }
    }

    #endregion
}
