// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/hero.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;
using Conf.Enums;

namespace Conf
{
    [Serializable]
    public partial struct HeroCfgId
    {
        public long Value;
        public readonly HeroCfg Cfg => ConfigAtlas.Instance.HeroTable[Value]!;
    }

    public partial class HeroTable : Dictionary<HeroCfgId, HeroCfg> { }

    public partial class HeroCfg
    {
        [JsonProperty("id")] public HeroCfgId Id { get; set; }
        /// <summary>Hero name</summary>
        [JsonProperty("name")] public L10n Name { get; set; }
        /// <summary>Title</summary>
        [JsonProperty("title")] public string Title { get; set; } = string.Empty;
        /// <summary>Class</summary>
        [JsonProperty("class")] public HeroClass Class { get; set; }
        /// <summary>Elements</summary>
        [JsonProperty("elements")] public Element Elements { get; set; }
        /// <summary>Level</summary>
        [JsonProperty("level")] public byte Level { get; set; }
        /// <summary>Luck</summary>
        [JsonProperty("luck")] public sbyte Luck { get; set; }
        /// <summary>Rank</summary>
        [JsonProperty("rank")] public short Rank { get; set; }
        /// <summary>Hit points</summary>
        [JsonProperty("hp")] public int Hp { get; set; }
        /// <summary>Mana</summary>
        [JsonProperty("mp")] public ushort Mp { get; set; }
        /// <summary>Fame</summary>
        [JsonProperty("fame")] public uint Fame { get; set; }
        /// <summary>Gold</summary>
        [JsonProperty("gold")] public long Gold { get; set; }
        /// <summary>Experience</summary>
        [JsonProperty("exp")] public ulong Exp { get; set; }
        /// <summary>Power</summary>
        [JsonProperty("power")] public long Power { get; set; }
        /// <summary>Souls</summary>
        [JsonProperty("souls")] public ulong Souls { get; set; }
        /// <summary>Critical rate</summary>
        [JsonProperty("critRate")] public float CritRate { get; set; }
        /// <summary>Dodge</summary>
        [JsonProperty("dodge")] public double Dodge { get; set; }
        /// <summary>Move speed</summary>
        [JsonProperty("moveSpeed")] public double MoveSpeed { get; set; }
        [JsonProperty("stats")] public Stats? Stats { get; set; }
        [JsonProperty("growth")] public Stats? Growth { get; set; }
        /// <summary>Birthday</summary>
        [JsonProperty("birthday")] public DateTimeOffset Birthday { get; set; }
        /// <summary>Respawn time</summary>
        [JsonProperty("respawn")] public Duration Respawn { get; set; }
        /// <summary>Theme color</summary>
        [JsonProperty("themeColor")] public Rgba ThemeColor { get; set; }
        /// <summary>Portrait</summary>
        [JsonProperty("portrait")] public string Portrait { get; set; } = string.Empty;
        /// <summary>Playable</summary>
        [JsonProperty("playable")] public bool Playable { get; set; }
        /// <summary>Weapon</summary>
        [JsonProperty("weapon")] public XRef<ItemCfgId, ItemCfg> Weapon { get; set; }
        /// <summary>Weapon ID</summary>
        [JsonProperty("weaponId")] public long WeaponId { get; set; }
        /// <summary>Race</summary>
        [JsonProperty("race")] public XRef<RaceCfgId, RaceCfg> Race { get; set; } = new(string.Empty, null);
        /// <summary>Spawn position</summary>
        [JsonProperty("spawnPos")] public Vec3<int> SpawnPos { get; set; }
        /// <summary>Facing</summary>
        [JsonProperty("facing")] public Vec2<float> Facing { get; set; }
        /// <summary>Talents</summary>
        [JsonProperty("talents")] public List<Hero_TalentsEntry>? Talents { get; set; }
    }

    // Stats represents $.*.stats
    public partial class Stats
    {
        /// <summary>Base HP</summary>
        [JsonProperty("hp")] public int Hp { get; set; }
        /// <summary>Base attack</summary>
        [JsonProperty("atk")] public float Atk { get; set; }
    }

    // Hero_TalentsEntry represents $.*.talents.*
    public partial class Hero_TalentsEntry
    {
        /// <summary>Skill</summary>
        [JsonProperty("skill")] public XRef<SkillCfgId, SkillCfg> Skill { get; set; } = new(string.Empty, null);
        /// <summary>Tier</summary>
        [JsonProperty("tier")] public sbyte Tier { get; set; }
    }

    public partial class HeroTable
    {
        public bool TryLookup(HeroCfgId cfgId, [NotNullWhen(true)] out HeroCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this, "HeroTable", out cfg);
        }

        public HeroCfg? Lookup(HeroCfgId cfgId)
        {
            return ConfigAtlas.Lookup(cfgId, this, "HeroTable");
        }

        internal XRef<HeroCfgId, HeroCfg> RefLookup(HeroCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup(cfgId, this, "HeroTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(HeroCfgIdJsonConverter))]
    [TypeConverter(typeof(HeroCfgIdTypeConverter))]
    public partial struct HeroCfgId : IEquatable<HeroCfgId>, IZero
    {
        public HeroCfgId(long value) { Value = value; }
        public static implicit operator HeroCfgId(long value) => new() { Value = value };
        public static implicit operator long(HeroCfgId obj) => obj.Value;

        public override readonly bool Equals(object? obj) => obj is HeroCfgId other && Equals(other);
        public readonly bool Equals(HeroCfgId other) => Value == other.Value;
        public override readonly int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(HeroCfgId left, HeroCfgId right) => left.Value == right.Value;
        public static bool operator !=(HeroCfgId left, HeroCfgId right) => left.Value != right.Value;

        public override readonly string ToString() => Value.ToString();
        public readonly bool IsZero => Value == 0;
    }

    class HeroCfgIdJsonConverter : ValueWrapperJsonConverter<HeroCfgId, long>
    {
        protected override HeroCfgId Create(long value) => value;
        protected override long GetValue(HeroCfgId obj) => obj.Value;
    }

    class HeroCfgIdTypeConverter : ValueWrapperTypeConverter<HeroCfgId, long>
    {
        protected override HeroCfgId Create(long value) => value;
    }

    public partial class HeroTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val is not null) val.Id = key;
            }
        }
    }

    public partial class HeroTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                v1?.BindRefs(atlas);
            }
        }
    }

    public partial class HeroCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Weapon = atlas.ItemTable.RefLookup(Weapon.CfgId);
            Race = atlas.RaceTable.RefLookup(Race.CfgId);
            if (Talents is not null)
            {
                foreach (var v1 in Talents)
                {
                    v1?.BindRefs(atlas);
                }
            }
        }
    }

    public partial class Hero_TalentsEntry
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Skill = atlas.SkillTable.RefLookup(Skill.CfgId);
        }
    }

    #endregion
}
