// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/hero.xlsx

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class HeroTable : Dictionary<long, HeroCfg?>
    {
        // Definition only.
    }

    public partial class HeroCfg
    {
        [JsonIgnore]
        public long Id { get; set; }
        [JsonProperty("heroName")]
        public L10n HeroName { get; set; }
        [JsonProperty("startLevel")]
        public long StartLevel { get; set; }
        [JsonProperty("referrer")]
        public List<XRef<long, RefCfg>>? Referrer { get; set; }
        [JsonProperty("race-combo")]
        public List<Hero_RaceComboEntry>? RaceCombo { get; set; }
        [JsonProperty("referrer-sort")]
        public List<XRef<long, RefCfg>>? ReferrerSort { get; set; }
        [JsonProperty("referrer-compact")]
        public List<XRef<long, RefCfg>>? ReferrerCompact { get; set; }
        [JsonProperty("referrer-sort-compact")]
        public List<XRef<long, RefCfg>>? ReferrerSortCompact { get; set; }
    }

    // Hero_RaceComboEntry represents $.*['race-combo'].*
    public partial class Hero_RaceComboEntry
    {
        [JsonProperty("race1")]
        public XRef<string, RaceCfg> Race1 { get; set; }
        [JsonProperty("race2")]
        public XRef<string, RaceCfg> Race2 { get; set; }
    }

    public partial class HeroTable
    {
        public bool TryLookup(long cfgID, out HeroCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgID, this!, "HeroTable", out cfg);
        }

        public HeroCfg? Lookup(long cfgID)
        {
            return ConfigAtlas.Lookup<long, HeroCfg>(cfgID, this!, "HeroTable");
        }

        internal XRef<long, HeroCfg> RefLookup(long cfgID)
        {
            return ConfigAtlas.MakeXRef(cfgID, ConfigAtlas.Lookup<long, HeroCfg>(cfgID, this!, "HeroTable"));
        }
    }

    #region Trifles

    public partial class HeroTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    public partial class HeroTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                if (v1 != null)
                    v1.BindRefs(atlas);
            }
        }
    }

    public partial class HeroCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            if (Referrer != null)
            {
                for (var i = 0; i < Referrer.Count; i++)
                {
                    Referrer[i] = atlas.RefTable.RefLookup(Referrer[i].RawValue);
                }
            }
            if (RaceCombo != null)
            {
                foreach (var v1 in RaceCombo)
                {
                    if (v1 != null)
                        v1.BindRefs(atlas);
                }
            }
            if (ReferrerSort != null)
            {
                for (var i = 0; i < ReferrerSort.Count; i++)
                {
                    ReferrerSort[i] = atlas.RefTable.RefLookup(ReferrerSort[i].RawValue);
                }
            }
            if (ReferrerCompact != null)
            {
                for (var i = 0; i < ReferrerCompact.Count; i++)
                {
                    ReferrerCompact[i] = atlas.RefTable.RefLookup(ReferrerCompact[i].RawValue);
                }
            }
            if (ReferrerSortCompact != null)
            {
                for (var i = 0; i < ReferrerSortCompact.Count; i++)
                {
                    ReferrerSortCompact[i] = atlas.RefTable.RefLookup(ReferrerSortCompact[i].RawValue);
                }
            }
        }
    }

    public partial class Hero_RaceComboEntry
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Race1 = atlas.RaceTable.RefLookup(Race1.RawValue);
            Race2 = atlas.RaceTable.RefLookup(Race2.RawValue);
        }
    }

    #endregion
}
