// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/item.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;
using Conf.Enums;

namespace Conf
{
    [Serializable]
    public partial struct ItemCfgId
    {
        public long Value;
        public readonly ItemCfg Cfg => ConfigAtlas.Instance.ItemTable[Value]!;
    }

    public partial class ItemTable : Dictionary<ItemCfgId, ItemCfg> { }

    public partial class ItemCfg
    {
        [JsonProperty("id")] public ItemCfgId Id { get; set; }
        /// <summary>Item name</summary>
        [JsonProperty("name")] public string Name { get; set; } = string.Empty;
        /// <summary>Rarity</summary>
        [JsonProperty("rarity")] public Rarity Rarity { get; set; }
        /// <summary>Price</summary>
        [JsonProperty("price")] public Price? Price { get; set; }
        /// <summary>Sell price</summary>
        [JsonProperty("sellPrice")] public Price? SellPrice { get; set; }
        /// <summary>Tags</summary>
        [JsonProperty("tags")] public List<string>? Tags { get; set; }
        /// <summary>Icon</summary>
        [JsonProperty("icon")] public string Icon { get; set; } = string.Empty;
        /// <summary>Stackable</summary>
        [JsonProperty("stackable")] public bool Stackable { get; set; }
        /// <summary>Best owner</summary>
        [JsonProperty("bestOwner")] public XRef<HeroCfgId, HeroCfg> BestOwner { get; set; }
        /// <summary>Enchantments</summary>
        [JsonProperty("enchants")] public List<Item_EnchantsEntry>? Enchants { get; set; }
    }

    // Price represents $.*.price
    public partial class Price
    {
        [JsonProperty("gold")] public int Gold { get; set; }
        [JsonProperty("gem")] public short Gem { get; set; }
    }

    // Item_EnchantsEntry represents $.*.enchants.*
    public partial class Item_EnchantsEntry
    {
        /// <summary>Element</summary>
        [JsonProperty("element")] public Element Element { get; set; }
        /// <summary>Bonus</summary>
        [JsonProperty("bonus")] public short Bonus { get; set; }
        /// <summary>Scroll</summary>
        [JsonProperty("scroll")] public XRef<ItemCfgId, ItemCfg> Scroll { get; set; }
    }

    public partial class ItemTable
    {
        public bool TryLookup(ItemCfgId cfgId, [NotNullWhen(true)] out ItemCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this, "ItemTable", out cfg);
        }

        public ItemCfg? Lookup(ItemCfgId cfgId)
        {
            return ConfigAtlas.Lookup(cfgId, this, "ItemTable");
        }

        internal XRef<ItemCfgId, ItemCfg> RefLookup(ItemCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup(cfgId, this, "ItemTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(ItemCfgIdJsonConverter))]
    [TypeConverter(typeof(ItemCfgIdTypeConverter))]
    public partial struct ItemCfgId : IEquatable<ItemCfgId>, IZero
    {
        public ItemCfgId(long value) { Value = value; }
        public static implicit operator ItemCfgId(long value) => new() { Value = value };
        public static implicit operator long(ItemCfgId obj) => obj.Value;

        public override readonly bool Equals(object? obj) => obj is ItemCfgId other && Equals(other);
        public readonly bool Equals(ItemCfgId other) => Value == other.Value;
        public override readonly int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(ItemCfgId left, ItemCfgId right) => left.Value == right.Value;
        public static bool operator !=(ItemCfgId left, ItemCfgId right) => left.Value != right.Value;

        public override readonly string ToString() => Value.ToString();
        public readonly bool IsZero => Value == 0;
    }

    class ItemCfgIdJsonConverter : ValueWrapperJsonConverter<ItemCfgId, long>
    {
        protected override ItemCfgId Create(long value) => value;
        protected override long GetValue(ItemCfgId obj) => obj.Value;
    }

    class ItemCfgIdTypeConverter : ValueWrapperTypeConverter<ItemCfgId, long>
    {
        protected override ItemCfgId Create(long value) => value;
    }

    public partial class ItemTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val is not null) val.Id = key;
            }
        }
    }

    public partial class ItemTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                v1?.BindRefs(atlas);
            }
        }
    }

    public partial class ItemCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            BestOwner = atlas.HeroTable.RefLookup(BestOwner.CfgId);
            if (Enchants is not null)
            {
                foreach (var v1 in Enchants)
                {
                    v1?.BindRefs(atlas);
                }
            }
        }
    }

    public partial class Item_EnchantsEntry
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Scroll = atlas.ItemTable.RefLookup(Scroll.CfgId);
        }
    }

    #endregion
}
