// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Item

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class ItemTable : Dictionary<long, ItemCfg?>
    {
        // Definition only.
    }

    public partial class ItemCfg
    {
        [JsonIgnore]
        public long Id { get; set; }
        [JsonProperty("name")]
        public string Name { get; set; } = null!;
        [JsonProperty("price")]
        public Item_Price? Price { get; set; }
    }

    // Item_Price represents $.*.price
    public partial class Item_Price
    {
        [JsonProperty("one")]
        public long One { get; set; }
        [JsonProperty("stack")]
        public long Stack { get; set; }
    }

    public partial class ItemTable
    {
        public bool TryLookup(long cfgID, out ItemCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgID, this!, "ItemTable", out cfg);
        }

        public ItemCfg? Lookup(long cfgID)
        {
            return ConfigAtlas.Lookup<long, ItemCfg>(cfgID, this!, "ItemTable");
        }

        internal XRef<long, ItemCfg> RefLookup(long cfgID)
        {
            return ConfigAtlas.MakeXRef(cfgID, ConfigAtlas.Lookup<long, ItemCfg>(cfgID, this!, "ItemTable"));
        }
    }

    #region Trifles

    public partial class ItemTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    #endregion
}
