// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Item

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial struct ItemCfgId
    {
        public long Value { get; internal set; }
    }

    public partial class ItemTable : Dictionary<ItemCfgId, ItemCfg?> {}

    public partial class ItemCfg
    {
        [JsonIgnore]
        public ItemCfgId Id { get; set; }
        [JsonProperty("name")]
        public string Name { get; set; } = null!;
        [JsonProperty("price")]
        public Item_Price? Price { get; set; }
    }

    // Item_Price represents $.*.price
    public partial class Item_Price
    {
        [JsonProperty("one")]
        public long One { get; set; }
        [JsonProperty("stack")]
        public long Stack { get; set; }
    }

    public partial class ItemTable
    {
        public bool TryLookup(ItemCfgId cfgID, out ItemCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgID, this!, "ItemTable", out cfg);
        }

        public ItemCfg? Lookup(ItemCfgId cfgID)
        {
            return ConfigAtlas.Lookup<ItemCfgId, ItemCfg>(cfgID, this!, "ItemTable");
        }

        internal XRef<ItemCfgId, ItemCfg> RefLookup(ItemCfgId cfgID)
        {
            return ConfigAtlas.MakeXRef(cfgID, ConfigAtlas.Lookup<ItemCfgId, ItemCfg>(cfgID, this!, "ItemTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(ItemCfgIdJsonConverter))]
    [TypeConverter(typeof(ItemCfgIdTypeConverter))]
    public partial struct ItemCfgId : IEquatable<ItemCfgId>, IZero
    {
        public static implicit operator ItemCfgId(long value) => new() { Value = value };
        public static implicit operator long(ItemCfgId obj) => obj.Value;

        public bool Equals(ItemCfgId other) => Value == other.Value;
        public override bool Equals(object? obj) => obj is ItemCfgId other && Equals(other);
        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(ItemCfgId left, ItemCfgId right) => left.Value == right.Value;
        public static bool operator !=(ItemCfgId left, ItemCfgId right) => left.Value != right.Value;

        public override string ToString() => Value.ToString();
        public bool IsZero => Value == default;
    }

    internal class ItemCfgIdJsonConverter : ValueWrapperJsonConverter<ItemCfgId, long>
    {
        protected override ItemCfgId Create(long value) => value;
        protected override long GetValue(ItemCfgId obj) => obj.Value;
    }

    internal class ItemCfgIdTypeConverter : ValueWrapperTypeConverter<ItemCfgId, long>
    {
        protected override ItemCfgId Create(long value) => value;
    }

    public partial class ItemTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    #endregion
}
