// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Magic

#nullable enable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class MagicTable : Dictionary<long, MagicCfg?>
    {
        // Definition only.
    }

    public partial class MagicCfg
    {
        [JsonIgnore]
        public long Id { get; set; }
        [JsonProperty("name")]
        public string Name { get; set; } = null!;
    }

    public partial class MagicTable
    {
        public bool TryLookup(long cfgID, out MagicCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgID, this!, "MagicTable", out cfg);
        }

        public MagicCfg? Lookup(long cfgID)
        {
            return ConfigAtlas.Lookup<long, MagicCfg>(cfgID, this!, "MagicTable");
        }

        internal XRef<long, MagicCfg> RefLookup(long cfgID)
        {
            return ConfigAtlas.MakeXRef(cfgID, ConfigAtlas.Lookup<long, MagicCfg>(cfgID, this!, "MagicTable"));
        }
    }

    #region Trifles

    public partial class MagicTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    #endregion
}
