// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/monster.json

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;
using Conf.Enums;

namespace Conf
{
    [Serializable]
    public partial struct MonsterCfgId
    {
        public long Value;
        public readonly MonsterCfg Cfg => ConfigAtlas.Instance.MonsterTable[Value]!;
    }

    public partial class MonsterTable : Dictionary<MonsterCfgId, MonsterCfg> { }

    public partial class MonsterCfg
    {
        [JsonProperty("id")] public MonsterCfgId Id { get; set; }
        [JsonProperty("name")] public string Name { get; set; } = string.Empty;
        [JsonProperty("habitat")] public XRef<RegionCfgId, RegionCfg> Habitat { get; set; } = new(string.Empty, null);
        [JsonProperty("resist")] public Dictionary<Element, long>? Resist { get; set; }
        [JsonProperty("size")] public List<float>? Size { get; set; }
        [JsonProperty("speed")] public Vec2<float> Speed { get; set; }
        [JsonProperty("aggro")] public MinMax<float> Aggro { get; set; }
        [JsonProperty("loot")] public WeightedPool<XRef<ItemCfgId, ItemCfg>>? Loot { get; set; }
        [JsonProperty("stats")] public Monster_Stats? Stats { get; set; }
        [JsonProperty("phases")] public List<Monster_PhasesEntry>? Phases { get; set; }
    }

    // Monster_Stats represents $.*.stats
    public partial class Monster_Stats
    {
        [JsonProperty("hp")] public long Hp { get; set; }
        [JsonProperty("atk")] public double Atk { get; set; }
    }

    // Monster_PhasesEntry represents $.*.phases.*
    public partial class Monster_PhasesEntry
    {
        [JsonProperty("hpBelow")] public long HpBelow { get; set; }
        [JsonProperty("summon")] public XRef<MonsterCfgId, MonsterCfg> Summon { get; set; }
        [JsonProperty("cast")] public XRef<SkillCfgId, SkillCfg> Cast { get; set; } = new(string.Empty, null);
    }

    public partial class MonsterTable
    {
        public bool TryLookup(MonsterCfgId cfgId, [NotNullWhen(true)] out MonsterCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this, "MonsterTable", out cfg);
        }

        public MonsterCfg? Lookup(MonsterCfgId cfgId)
        {
            return ConfigAtlas.Lookup(cfgId, this, "MonsterTable");
        }

        internal XRef<MonsterCfgId, MonsterCfg> RefLookup(MonsterCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup(cfgId, this, "MonsterTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(MonsterCfgIdJsonConverter))]
    [TypeConverter(typeof(MonsterCfgIdTypeConverter))]
    public partial struct MonsterCfgId : IEquatable<MonsterCfgId>, IZero
    {
        public MonsterCfgId(long value) { Value = value; }
        public static implicit operator MonsterCfgId(long value) => new() { Value = value };
        public static implicit operator long(MonsterCfgId obj) => obj.Value;

        public override readonly bool Equals(object? obj) => obj is MonsterCfgId other && Equals(other);
        public readonly bool Equals(MonsterCfgId other) => Value == other.Value;
        public override readonly int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(MonsterCfgId left, MonsterCfgId right) => left.Value == right.Value;
        public static bool operator !=(MonsterCfgId left, MonsterCfgId right) => left.Value != right.Value;

        public override readonly string ToString() => Value.ToString();
        public readonly bool IsZero => Value == 0;
    }

    class MonsterCfgIdJsonConverter : ValueWrapperJsonConverter<MonsterCfgId, long>
    {
        protected override MonsterCfgId Create(long value) => value;
        protected override long GetValue(MonsterCfgId obj) => obj.Value;
    }

    class MonsterCfgIdTypeConverter : ValueWrapperTypeConverter<MonsterCfgId, long>
    {
        protected override MonsterCfgId Create(long value) => value;
    }

    public partial class MonsterTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val is not null) val.Id = key;
            }
        }
    }

    public partial class MonsterTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                v1?.BindRefs(atlas);
            }
        }
    }

    public partial class MonsterCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Habitat = atlas.RegionTable.RefLookup(Habitat.CfgId);
            if (Loot?.Items is not null)
            {
                for (var i = 0; i < Loot.Items.Length; i++)
                {
                    Loot.Items[i] = atlas.ItemTable.RefLookup(Loot.Items[i].CfgId);
                }
            }
            if (Phases is not null)
            {
                foreach (var v1 in Phases)
                {
                    v1?.BindRefs(atlas);
                }
            }
        }
    }

    public partial class Monster_PhasesEntry
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Summon = atlas.MonsterTable.RefLookup(Summon.CfgId);
            Cast = atlas.SkillTable.RefLookup(Cast.CfgId);
        }
    }

    #endregion
}
