// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/prop_floats.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class PropFloatsCfg
    {
        // desc-B
        [JsonProperty("B")]
        public double B { get; set; }
        // desc-C
        [JsonProperty("C")]
        public float C { get; set; }
        // desc-D
        [JsonProperty("D")]
        public double D { get; set; }
        // desc-E
        [JsonProperty("E")]
        public float E { get; set; }
        // desc-F
        [JsonProperty("F")]
        public double F { get; set; }
        // desc-G
        [JsonProperty("G")]
        public double G { get; set; }
    }

    #region Trifles

    #endregion
}
