// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Race

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial struct RaceCfgId
    {
        public string Value { get; internal set; }
    }

    public partial class RaceTable : Dictionary<RaceCfgId, RaceCfg> {}

    public partial class RaceCfg
    {
        [JsonProperty("id")]
        public RaceCfgId Id { get; set; } = string.Empty;
        [JsonProperty("birthplace")]
        public L10n Birthplace { get; set; }
        [JsonProperty("referrer1")]
        public XRef<RefCfgId, RefCfg> Referrer1 { get; set; }
        [JsonProperty("referrer2")]
        public XRef<StringCfgId, StringCfg> Referrer2 { get; set; }
        [JsonProperty("heroes1")]
        public List<XRef<HeroCfgId, HeroCfg>>? Heroes1 { get; set; }
        [JsonProperty("heroes2")]
        public List<XRef<HeroCfgId, HeroCfg>>? Heroes2 { get; set; }
    }

    public partial class RaceTable
    {
        public bool TryLookup(RaceCfgId cfgId, out RaceCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this!, "RaceTable", out cfg);
        }

        public RaceCfg? Lookup(RaceCfgId cfgId)
        {
            return ConfigAtlas.Lookup<RaceCfgId, RaceCfg>(cfgId, this!, "RaceTable");
        }

        internal XRef<RaceCfgId, RaceCfg> RefLookup(RaceCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup<RaceCfgId, RaceCfg>(cfgId, this!, "RaceTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(RaceCfgIdJsonConverter))]
    [TypeConverter(typeof(RaceCfgIdTypeConverter))]
    public partial struct RaceCfgId : IEquatable<RaceCfgId>, IZero
    {
        public static implicit operator RaceCfgId(string value) => new() { Value = value };
        public static implicit operator string(RaceCfgId obj) => obj.Value;

        public bool Equals(RaceCfgId other) => Value == other.Value;
        public override bool Equals(object? obj) => obj is RaceCfgId other && Equals(other);
        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(RaceCfgId left, RaceCfgId right) => left.Value == right.Value;
        public static bool operator !=(RaceCfgId left, RaceCfgId right) => left.Value != right.Value;

        public override string ToString() => Value;
        public bool IsZero => string.IsNullOrEmpty(Value);
    }

    internal class RaceCfgIdJsonConverter : ValueWrapperJsonConverter<RaceCfgId, string>
    {
        protected override RaceCfgId Create(string value) => value;
        protected override string GetValue(RaceCfgId obj) => obj.Value;
    }

    internal class RaceCfgIdTypeConverter : ValueWrapperTypeConverter<RaceCfgId, string>
    {
        protected override RaceCfgId Create(string value) => value;
    }

    public partial class RaceTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    public partial class RaceTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                if (v1 != null)
                    v1.BindRefs(atlas);
            }
        }
    }

    public partial class RaceCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Referrer1 = atlas.RefTable.RefLookup(Referrer1.CfgId);
            Referrer2 = atlas.StringTable.RefLookup(Referrer2.CfgId);
            if (Heroes1 != null)
            {
                for (var i = 0; i < Heroes1.Count; i++)
                {
                    Heroes1[i] = atlas.HeroTable.RefLookup(Heroes1[i].CfgId);
                }
            }
            if (Heroes2 != null)
            {
                for (var i = 0; i < Heroes2.Count; i++)
                {
                    Heroes2[i] = atlas.HeroTable.RefLookup(Heroes2[i].CfgId);
                }
            }
        }
    }

    #endregion
}
