// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/ref.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial struct RefCfgId
    {
        public long Value { get; internal set; }
    }

    public partial class RefTable : Dictionary<RefCfgId, RefCfg> {}

    public partial class RefCfg
    {
        [JsonProperty("id")]
        public RefCfgId Id { get; set; }
        /// <summary>desc-B</summary>
        [JsonProperty("B")]
        public XRef<WeaponRuneCfgId, WeaponRuneCfg> B { get; set; }
        /// <summary>desc-C</summary>
        [JsonProperty("C")]
        public long C { get; set; }
        /// <summary>desc-D</summary>
        [JsonProperty("D")]
        public XRef<ItemCfgId, ItemCfg> D { get; set; }
        /// <summary>desc-E</summary>
        [JsonProperty("E")]
        public XRef<MagicCfgId, MagicCfg> E { get; set; }
        /// <summary>desc-F</summary>
        [JsonProperty("F")]
        public XRef<RaceCfgId, RaceCfg> F { get; set; }
        /// <summary>desc-G</summary>
        [JsonProperty("G")]
        public XRef<HeroCfgId, HeroCfg> G { get; set; }
        /// <summary>desc-H</summary>
        [JsonProperty("H")]
        public List<XRef<StringCfgId, StringCfg>>? H { get; set; }
        /// <summary>desc-J</summary>
        [JsonProperty("J")]
        public XRef<ItemCfgId, ItemCfg> J { get; set; }
        /// <summary>desc-K</summary>
        [JsonProperty("K")]
        public XRef<RaceCfgId, RaceCfg> K { get; set; }
    }

    public partial class RefTable
    {
        public bool TryLookup(RefCfgId cfgId, out RefCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this!, "RefTable", out cfg);
        }

        public RefCfg? Lookup(RefCfgId cfgId)
        {
            return ConfigAtlas.Lookup<RefCfgId, RefCfg>(cfgId, this!, "RefTable");
        }

        internal XRef<RefCfgId, RefCfg> RefLookup(RefCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup<RefCfgId, RefCfg>(cfgId, this!, "RefTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(RefCfgIdJsonConverter))]
    [TypeConverter(typeof(RefCfgIdTypeConverter))]
    public partial struct RefCfgId : IEquatable<RefCfgId>, IZero
    {
        public static implicit operator RefCfgId(long value) => new() { Value = value };
        public static implicit operator long(RefCfgId obj) => obj.Value;

        public bool Equals(RefCfgId other) => Value == other.Value;
        public override bool Equals(object? obj) => obj is RefCfgId other && Equals(other);
        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(RefCfgId left, RefCfgId right) => left.Value == right.Value;
        public static bool operator !=(RefCfgId left, RefCfgId right) => left.Value != right.Value;

        public override string ToString() => Value.ToString();
        public bool IsZero => Value == default;
    }

    internal class RefCfgIdJsonConverter : ValueWrapperJsonConverter<RefCfgId, long>
    {
        protected override RefCfgId Create(long value) => value;
        protected override long GetValue(RefCfgId obj) => obj.Value;
    }

    internal class RefCfgIdTypeConverter : ValueWrapperTypeConverter<RefCfgId, long>
    {
        protected override RefCfgId Create(long value) => value;
    }

    public partial class RefTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    public partial class RefTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                if (v1 != null)
                    v1.BindRefs(atlas);
            }
        }
    }

    public partial class RefCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            B = atlas.WeaponRuneTable.RefLookup(B.CfgId);
            D = atlas.ItemTable.RefLookup(D.CfgId);
            E = atlas.MagicTable.RefLookup(E.CfgId);
            F = atlas.RaceTable.RefLookup(F.CfgId);
            G = atlas.HeroTable.RefLookup(G.CfgId);
            if (H != null)
            {
                for (var i1 = 0; i1 < H.Count; i1++)
                {
                    H[i1] = atlas.StringTable.RefLookup(H[i1].CfgId);
                }
            }
            J = atlas.ItemTable.RefLookup(J.CfgId);
            K = atlas.RaceTable.RefLookup(K.CfgId);
        }
    }

    #endregion
}
