// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/world.xlsx::Region

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;

namespace Conf
{
    [Serializable]
    public partial struct RegionCfgId
    {
        public string Value;
        public readonly RegionCfg Cfg => ConfigAtlas.Instance.RegionTable[Value]!;
    }

    public partial class RegionTable : Dictionary<RegionCfgId, RegionCfg> { }

    public partial class RegionCfg
    {
        [JsonProperty("id")] public RegionCfgId Id { get; set; } = string.Empty;
        /// <summary>Region name</summary>
        [JsonProperty("name")] public string Name { get; set; } = string.Empty;
        /// <summary>Climate</summary>
        [JsonProperty("climate")] public string Climate { get; set; } = string.Empty;
        /// <summary>Neighbors</summary>
        [JsonProperty("neighbors")] public List<XRef<RegionCfgId, RegionCfg>>? Neighbors { get; set; }
        /// <summary>Monsters</summary>
        [JsonProperty("monsters")] public List<XRef<MonsterCfgId, MonsterCfg>>? Monsters { get; set; }
    }

    public partial class RegionTable
    {
        public bool TryLookup(RegionCfgId cfgId, [NotNullWhen(true)] out RegionCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this, "RegionTable", out cfg);
        }

        public RegionCfg? Lookup(RegionCfgId cfgId)
        {
            return ConfigAtlas.Lookup(cfgId, this, "RegionTable");
        }

        internal XRef<RegionCfgId, RegionCfg> RefLookup(RegionCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup(cfgId, this, "RegionTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(RegionCfgIdJsonConverter))]
    [TypeConverter(typeof(RegionCfgIdTypeConverter))]
    public partial struct RegionCfgId : IEquatable<RegionCfgId>, IZero
    {
        public RegionCfgId(string value) { Value = value; }
        public static implicit operator RegionCfgId(string value) => new() { Value = value };
        public static implicit operator string(RegionCfgId obj) => obj.Value ?? string.Empty;

        public override readonly bool Equals(object? obj) => obj is RegionCfgId other && Equals(other);
        public readonly bool Equals(RegionCfgId other) => (Value ?? string.Empty) == (other.Value ?? string.Empty);
        public override readonly int GetHashCode() => (Value ?? string.Empty).GetHashCode();

        public static bool operator ==(RegionCfgId left, RegionCfgId right) => left.Equals(right);
        public static bool operator !=(RegionCfgId left, RegionCfgId right) => !left.Equals(right);

        public override readonly string ToString() => Value ?? string.Empty;
        public bool IsZero => string.IsNullOrEmpty(Value);
    }

    class RegionCfgIdJsonConverter : ValueWrapperJsonConverter<RegionCfgId, string>
    {
        protected override RegionCfgId Create(string value) => value;
        protected override string GetValue(RegionCfgId obj) => obj.Value ?? string.Empty;
    }

    class RegionCfgIdTypeConverter : ValueWrapperTypeConverter<RegionCfgId, string>
    {
        protected override RegionCfgId Create(string value) => value;
    }

    public partial class RegionTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val is not null) val.Id = key;
            }
        }
    }

    public partial class RegionTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                v1?.BindRefs(atlas);
            }
        }
    }

    public partial class RegionCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            if (Neighbors is not null)
            {
                for (var i1 = 0; i1 < Neighbors.Count; i1++)
                {
                    Neighbors[i1] = atlas.RegionTable.RefLookup(Neighbors[i1].CfgId);
                }
            }
            if (Monsters is not null)
            {
                for (var i = 0; i < Monsters.Count; i++)
                {
                    Monsters[i] = atlas.MonsterTable.RefLookup(Monsters[i].CfgId);
                }
            }
        }
    }

    #endregion
}
