// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/string.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial struct StringCfgId
    {
        public string Value { get; internal set; }
    }

    public partial class StringTable : Dictionary<StringCfgId, StringCfg?> {}

    public partial class StringCfg
    {
        [JsonIgnore]
        public StringCfgId Id { get; set; } = null!;
        [JsonProperty("B")]
        public String_B? B { get; set; }
        // desc-E
        [JsonProperty("E")]
        public string E { get; set; } = null!;
        // def-validate
        [JsonProperty("def-validate")]
        public string DefValidate { get; set; } = null!;
        // def-postprocess
        [JsonProperty("def-postprocess")]
        public string DefPostprocess { get; set; } = null!;
        // desc-I
        [JsonProperty("I")]
        public string I { get; set; } = null!;
        // desc-K
        [JsonProperty("K")]
        public XRef<RaceCfgId, RaceCfg> K { get; set; }
        // desc-referer1
        [JsonProperty("referer1")]
        public XRef<RefCfgId, RefCfg> Referer1 { get; set; }
        // desc-referer2
        [JsonProperty("referer2")]
        public XRef<RefCfgId, RefCfg> Referer2 { get; set; }
        // desc-referer-n
        [JsonProperty("referer-n")]
        public List<XRef<RefCfgId, RefCfg>>? RefererN { get; set; }
    }

    // String_B represents $.*.B
    public partial class String_B
    {
        [JsonProperty("bar")]
        public Rab? Bar { get; set; }
        // desc-B.car
        [JsonProperty("car")]
        public string Car { get; set; } = null!;
    }

    // Rab represents $.*.B.bar
    public partial class Rab
    {
        // desc-B.bar.foo
        [JsonProperty("foo")]
        public string Foo { get; set; } = null!;
        // desc-B.bar.qux
        [JsonProperty("qux")]
        public string Qux { get; set; } = null!;
    }

    public partial class StringTable
    {
        public bool TryLookup(StringCfgId cfgID, out StringCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgID, this!, "StringTable", out cfg);
        }

        public StringCfg? Lookup(StringCfgId cfgID)
        {
            return ConfigAtlas.Lookup<StringCfgId, StringCfg>(cfgID, this!, "StringTable");
        }

        internal XRef<StringCfgId, StringCfg> RefLookup(StringCfgId cfgID)
        {
            return ConfigAtlas.MakeXRef(cfgID, ConfigAtlas.Lookup<StringCfgId, StringCfg>(cfgID, this!, "StringTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(StringCfgIdJsonConverter))]
    [TypeConverter(typeof(StringCfgIdTypeConverter))]
    public partial struct StringCfgId : IEquatable<StringCfgId>, IZero
    {
        public static implicit operator StringCfgId(string value) => new() { Value = value };
        public static implicit operator string(StringCfgId obj) => obj.Value;

        public bool Equals(StringCfgId other) => Value == other.Value;
        public override bool Equals(object? obj) => obj is StringCfgId other && Equals(other);
        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(StringCfgId left, StringCfgId right) => left.Value == right.Value;
        public static bool operator !=(StringCfgId left, StringCfgId right) => left.Value != right.Value;

        public override string ToString() => Value;
        public bool IsZero => string.IsNullOrEmpty(Value);
    }

    internal class StringCfgIdJsonConverter : ValueWrapperJsonConverter<StringCfgId, string>
    {
        protected override StringCfgId Create(string value) => value;
        protected override string GetValue(StringCfgId obj) => obj.Value;
    }

    internal class StringCfgIdTypeConverter : ValueWrapperTypeConverter<StringCfgId, string>
    {
        protected override StringCfgId Create(string value) => value;
    }

    public partial class StringTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    public partial class StringTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                if (v1 != null)
                    v1.BindRefs(atlas);
            }
        }
    }

    public partial class StringCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            K = atlas.RaceTable.RefLookup(K.RawValue);
            Referer1 = atlas.RefTable.RefLookup(Referer1.RawValue);
            Referer2 = atlas.RefTable.RefLookup(Referer2.RawValue);
            if (RefererN != null)
            {
                for (var i = 0; i < RefererN.Count; i++)
                {
                    RefererN[i] = atlas.RefTable.RefLookup(RefererN[i].RawValue);
                }
            }
        }
    }

    #endregion
}
