// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/string.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;

namespace Conf
{
    public partial struct StringCfgId
    {
        public string Value { get; internal set; }
    }

    public partial class StringTable : Dictionary<StringCfgId, StringCfg> {}

    public partial class StringCfg
    {
        [JsonProperty("id")]
        public StringCfgId Id { get; set; } = string.Empty;
        [JsonProperty("B")]
        public String_B? B { get; set; }
        /// <summary>desc-E</summary>
        [JsonProperty("E")]
        public string E { get; set; } = string.Empty;
        /// <summary>def-validate</summary>
        [JsonProperty("def-validate")]
        public string DefValidate { get; set; } = string.Empty;
        /// <summary>def-postprocess</summary>
        [JsonProperty("def-postprocess")]
        public string DefPostprocess { get; set; } = string.Empty;
        /// <summary>desc-I</summary>
        [JsonProperty("I")]
        public string I { get; set; } = string.Empty;
        /// <summary>desc-K</summary>
        [JsonProperty("K")]
        public XRef<RaceCfgId, RaceCfg> K { get; set; }
        /// <summary>desc-referer1</summary>
        [JsonProperty("referer1")]
        public XRef<RefCfgId, RefCfg> Referer1 { get; set; }
        /// <summary>desc-referer2</summary>
        [JsonProperty("referer2")]
        public XRef<RefCfgId, RefCfg> Referer2 { get; set; }
        /// <summary>desc-referer-n</summary>
        [JsonProperty("referer-n")]
        public List<XRef<RefCfgId, RefCfg>>? RefererN { get; set; }
    }

    // String_B represents $.*.B
    public partial class String_B
    {
        [JsonProperty("bar")]
        public Rab? Bar { get; set; }
        /// <summary>desc-B.car</summary>
        [JsonProperty("car")]
        public string Car { get; set; } = string.Empty;
    }

    // Rab represents $.*.B.bar
    public partial class Rab
    {
        /// <summary>desc-B.bar.foo</summary>
        [JsonProperty("foo")]
        public string Foo { get; set; } = string.Empty;
        /// <summary>desc-B.bar.qux</summary>
        [JsonProperty("qux")]
        public string Qux { get; set; } = string.Empty;
    }

    public partial class StringTable
    {
        public bool TryLookup(StringCfgId cfgId, out StringCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this!, "StringTable", out cfg);
        }

        public StringCfg? Lookup(StringCfgId cfgId)
        {
            return ConfigAtlas.Lookup<StringCfgId, StringCfg>(cfgId, this!, "StringTable");
        }

        internal XRef<StringCfgId, StringCfg> RefLookup(StringCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup<StringCfgId, StringCfg>(cfgId, this!, "StringTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(StringCfgIdJsonConverter))]
    [TypeConverter(typeof(StringCfgIdTypeConverter))]
    public partial struct StringCfgId : IEquatable<StringCfgId>, IZero
    {
        public static implicit operator StringCfgId(string value) => new() { Value = value };
        public static implicit operator string(StringCfgId obj) => obj.Value;

        public bool Equals(StringCfgId other) => Value == other.Value;
        public override bool Equals(object? obj) => obj is StringCfgId other && Equals(other);
        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(StringCfgId left, StringCfgId right) => left.Value == right.Value;
        public static bool operator !=(StringCfgId left, StringCfgId right) => left.Value != right.Value;

        public override string ToString() => Value;
        public bool IsZero => string.IsNullOrEmpty(Value);
    }

    internal class StringCfgIdJsonConverter : ValueWrapperJsonConverter<StringCfgId, string>
    {
        protected override StringCfgId Create(string value) => value;
        protected override string GetValue(StringCfgId obj) => obj.Value;
    }

    internal class StringCfgIdTypeConverter : ValueWrapperTypeConverter<StringCfgId, string>
    {
        protected override StringCfgId Create(string value) => value;
    }

    public partial class StringTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    public partial class StringTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                if (v1 != null)
                    v1.BindRefs(atlas);
            }
        }
    }

    public partial class StringCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            K = atlas.RaceTable.RefLookup(K.CfgId);
            Referer1 = atlas.RefTable.RefLookup(Referer1.CfgId);
            Referer2 = atlas.RefTable.RefLookup(Referer2.CfgId);
            if (RefererN != null)
            {
                for (var i = 0; i < RefererN.Count; i++)
                {
                    RefererN[i] = atlas.RefTable.RefLookup(RefererN[i].CfgId);
                }
            }
        }
    }

    #endregion
}
