// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/string.xlsx

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class StringTable : Dictionary<string, StringCfg?>
    {
        // Definition only.
    }

    public partial class StringCfg
    {
        [JsonIgnore]
        public string Id { get; set; } = null!;
        [JsonProperty("B")]
        public String_B? B { get; set; }
        /// <summary>
        /// desc-E
        /// </summary>
        [JsonProperty("E")]
        public string E { get; set; } = null!;
        /// <summary>
        /// def-validate
        /// </summary>
        [JsonProperty("def-validate")]
        public string DefValidate { get; set; } = null!;
        /// <summary>
        /// def-postprocess
        /// </summary>
        [JsonProperty("def-postprocess")]
        public string DefPostprocess { get; set; } = null!;
        /// <summary>
        /// desc-I
        /// </summary>
        [JsonProperty("I")]
        public string I { get; set; } = null!;
        /// <summary>
        /// desc-K
        /// </summary>
        [JsonProperty("K")]
        public Ref<string, RaceCfg> K { get; set; }
        /// <summary>
        /// desc-referer1
        /// </summary>
        [JsonProperty("referer1")]
        public Ref<long, RefCfg> Referer1 { get; set; }
        /// <summary>
        /// desc-referer2
        /// </summary>
        [JsonProperty("referer2")]
        public Ref<long, RefCfg> Referer2 { get; set; }
        /// <summary>
        /// desc-referer-n
        /// </summary>
        [JsonProperty("referer-n")]
        public List<Ref<long, RefCfg>>? RefererN { get; set; }
    }

    // String_B represents $.*.B
    public partial class String_B
    {
        [JsonProperty("bar")]
        public Rab? Bar { get; set; }
        /// <summary>
        /// desc-B.car
        /// </summary>
        [JsonProperty("car")]
        public string Car { get; set; } = null!;
    }

    // Rab represents $.*.B.bar
    public partial class Rab
    {
        /// <summary>
        /// desc-B.bar.foo
        /// </summary>
        [JsonProperty("foo")]
        public string Foo { get; set; } = null!;
        /// <summary>
        /// desc-B.bar.qux
        /// </summary>
        [JsonProperty("qux")]
        public string Qux { get; set; } = null!;
    }

    public partial class StringTable
    {
        public bool TryLookup(string cfgID, out StringCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgID, this!, "StringTable", out cfg);
        }

        public StringCfg? Lookup(string cfgID)
        {
            return ConfigAtlas.Lookup<string, StringCfg>(cfgID, this!, "StringTable");
        }

        internal Ref<string, StringCfg> RefLookup(string cfgID)
        {
            return ConfigAtlas.MakeRef(cfgID, ConfigAtlas.Lookup<string, StringCfg>(cfgID, this!, "StringTable"));
        }
    }

    #region Trifles

    public partial class StringTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    public partial class StringTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                if (v1 != null)
                    v1.BindRefs(atlas);
            }
        }
    }

    public partial class StringCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            K = atlas.RaceTable.RefLookup(K.RawValue);
            Referer1 = atlas.RefTable.RefLookup(Referer1.RawValue);
            Referer2 = atlas.RefTable.RefLookup(Referer2.RawValue);
            if (RefererN != null)
            {
                for (var i = 0; i < RefererN.Count; i++)
                {
                    RefererN[i] = atlas.RefTable.RefLookup(RefererN[i].RawValue);
                }
            }
        }
    }

    #endregion
}
