// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtItemX (virtual table)

#nullable enable

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class VtItemXTable : Dictionary<long, VtItemXCfg?>
    {
        // Definition only.
    }

    public partial class VtItemXCfg
    {
        [JsonIgnore]
        public long Id { get; set; }
        [JsonProperty("name")]
        public string Name { get; set; } = null!;
        [JsonProperty("price")]
        public long Price { get; set; }
        [JsonProperty("desc")]
        public string Desc { get; set; } = null!;
        [JsonProperty("special-skill")]
        public long SpecialSkill { get; set; }
        [JsonProperty("armor")]
        public float Armor { get; set; }
        [JsonProperty("dps")]
        public float Dps { get; set; }
        [JsonProperty("shield-skills")]
        public List<long>? ShieldSkills { get; set; }
        [JsonProperty("power")]
        public float Power { get; set; }
        [JsonProperty("attributeBonus")]
        public List<VtItemX_AttributeBonusEntry>? AttributeBonus { get; set; }
    }

    // VtItemX_AttributeBonusEntry represents $.*.attributeBonus.*
    public partial class VtItemX_AttributeBonusEntry
    {
        [JsonProperty("attr")]
        public string Attr { get; set; } = null!;
        [JsonProperty("bonus")]
        public long Bonus { get; set; }
    }

    public partial class VtItemXTable
    {
        public bool TryLookup(long cfgID, out VtItemXCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgID, this!, "VtItemXTable", out cfg);
        }

        public VtItemXCfg? Lookup(long cfgID)
        {
            return ConfigAtlas.Lookup<long, VtItemXCfg>(cfgID, this!, "VtItemXTable");
        }

        internal XRef<long, VtItemXCfg> RefLookup(long cfgID)
        {
            return ConfigAtlas.MakeXRef(cfgID, ConfigAtlas.Lookup<long, VtItemXCfg>(cfgID, this!, "VtItemXTable"));
        }
    }

    #region Trifles

    public partial class VtItemXTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    #endregion
}
