// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtItemX (virtual table)

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial struct VtItemXCfgId
    {
        public long Value { get; internal set; }
    }

    public partial class VtItemXTable : Dictionary<VtItemXCfgId, VtItemXCfg> {}

    public partial class VtItemXCfg
    {
        [JsonProperty("id")]
        public VtItemXCfgId Id { get; set; }
        [JsonProperty("name")]
        public string Name { get; set; } = string.Empty;
        [JsonProperty("price")]
        public long Price { get; set; }
        [JsonProperty("desc")]
        public string Desc { get; set; } = string.Empty;
        [JsonProperty("special-skill")]
        public long SpecialSkill { get; set; }
        [JsonProperty("armor")]
        public float Armor { get; set; }
        [JsonProperty("dps")]
        public float Dps { get; set; }
        [JsonProperty("shield-skills")]
        public List<long>? ShieldSkills { get; set; }
        [JsonProperty("power")]
        public float Power { get; set; }
        [JsonProperty("attributeBonus")]
        public List<VtItemX_AttributeBonusEntry>? AttributeBonus { get; set; }
    }

    // VtItemX_AttributeBonusEntry represents $.*.attributeBonus.*
    public partial class VtItemX_AttributeBonusEntry
    {
        [JsonProperty("attr")]
        public string Attr { get; set; } = string.Empty;
        [JsonProperty("bonus")]
        public long Bonus { get; set; }
    }

    public partial class VtItemXTable
    {
        public bool TryLookup(VtItemXCfgId cfgId, out VtItemXCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this!, "VtItemXTable", out cfg);
        }

        public VtItemXCfg? Lookup(VtItemXCfgId cfgId)
        {
            return ConfigAtlas.Lookup<VtItemXCfgId, VtItemXCfg>(cfgId, this!, "VtItemXTable");
        }

        internal XRef<VtItemXCfgId, VtItemXCfg> RefLookup(VtItemXCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup<VtItemXCfgId, VtItemXCfg>(cfgId, this!, "VtItemXTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(VtItemXCfgIdJsonConverter))]
    [TypeConverter(typeof(VtItemXCfgIdTypeConverter))]
    public partial struct VtItemXCfgId : IEquatable<VtItemXCfgId>, IZero
    {
        public static implicit operator VtItemXCfgId(long value) => new() { Value = value };
        public static implicit operator long(VtItemXCfgId obj) => obj.Value;

        public bool Equals(VtItemXCfgId other) => Value == other.Value;
        public override bool Equals(object? obj) => obj is VtItemXCfgId other && Equals(other);
        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(VtItemXCfgId left, VtItemXCfgId right) => left.Value == right.Value;
        public static bool operator !=(VtItemXCfgId left, VtItemXCfgId right) => left.Value != right.Value;

        public override string ToString() => Value.ToString();
        public bool IsZero => Value == default;
    }

    internal class VtItemXCfgIdJsonConverter : ValueWrapperJsonConverter<VtItemXCfgId, long>
    {
        protected override VtItemXCfgId Create(long value) => value;
        protected override long GetValue(VtItemXCfgId obj) => obj.Value;
    }

    internal class VtItemXCfgIdTypeConverter : ValueWrapperTypeConverter<VtItemXCfgId, long>
    {
        protected override VtItemXCfgId Create(long value) => value;
    }

    public partial class VtItemXTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    #endregion
}
