// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtQuest (virtual table)

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;

namespace Conf
{
    [Serializable]
    public partial struct VtQuestCfgId
    {
        public long Value;
        public readonly VtQuestCfg Cfg => ConfigAtlas.Instance.VtQuestTable[Value]!;
    }

    public partial class VtQuestTable : Dictionary<VtQuestCfgId, VtQuestCfg> { }

    public partial class VtQuestCfg
    {
        [JsonProperty("id")] public VtQuestCfgId Id { get; set; }
        [JsonProperty("name")] public string Name { get; set; } = string.Empty;
        [JsonProperty("chosenBy")] public List<long>? ChosenBy { get; set; }
        [JsonProperty("nextQuest")] public long NextQuest { get; set; }
        [JsonProperty("desc")] public L10n Desc { get; set; }
        [JsonProperty("origin")] public string Origin { get; set; } = string.Empty;
        [JsonProperty("unlockedBy")] public long UnlockedBy { get; set; }
        [JsonProperty("refreshInterval")] public MinMax<Duration> RefreshInterval { get; set; }
    }

    public partial class VtQuestTable
    {
        public bool TryLookup(VtQuestCfgId cfgId, [NotNullWhen(true)] out VtQuestCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this, "VtQuestTable", out cfg);
        }

        public VtQuestCfg? Lookup(VtQuestCfgId cfgId)
        {
            return ConfigAtlas.Lookup(cfgId, this, "VtQuestTable");
        }

        internal XRef<VtQuestCfgId, VtQuestCfg> RefLookup(VtQuestCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup(cfgId, this, "VtQuestTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(VtQuestCfgIdJsonConverter))]
    [TypeConverter(typeof(VtQuestCfgIdTypeConverter))]
    public partial struct VtQuestCfgId : IEquatable<VtQuestCfgId>, IZero
    {
        public VtQuestCfgId(long value) { Value = value; }
        public static implicit operator VtQuestCfgId(long value) => new() { Value = value };
        public static implicit operator long(VtQuestCfgId obj) => obj.Value;

        public override readonly bool Equals(object? obj) => obj is VtQuestCfgId other && Equals(other);
        public readonly bool Equals(VtQuestCfgId other) => Value == other.Value;
        public override readonly int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(VtQuestCfgId left, VtQuestCfgId right) => left.Value == right.Value;
        public static bool operator !=(VtQuestCfgId left, VtQuestCfgId right) => left.Value != right.Value;

        public override readonly string ToString() => Value.ToString();
        public readonly bool IsZero => Value == 0;
    }

    class VtQuestCfgIdJsonConverter : ValueWrapperJsonConverter<VtQuestCfgId, long>
    {
        protected override VtQuestCfgId Create(long value) => value;
        protected override long GetValue(VtQuestCfgId obj) => obj.Value;
    }

    class VtQuestCfgIdTypeConverter : ValueWrapperTypeConverter<VtQuestCfgId, long>
    {
        protected override VtQuestCfgId Create(long value) => value;
    }

    public partial class VtQuestTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val is not null) val.Id = key;
            }
        }
    }

    #endregion
}
