// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: vtSkill (virtual table)

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;
using Shadop.Archmage.Sdk;

namespace Conf
{
    [Serializable]
    public partial struct VtSkillCfgId
    {
        public string Value;
        public readonly VtSkillCfg Cfg => ConfigAtlas.Instance.VtSkillTable[Value]!;
    }

    public partial class VtSkillTable : Dictionary<VtSkillCfgId, VtSkillCfg> { }

    public partial class VtSkillCfg
    {
        [JsonProperty("id")] public VtSkillCfgId Id { get; set; } = string.Empty;
        [JsonProperty("name")] public string Name { get; set; } = string.Empty;
        [JsonProperty("class")] public string Class { get; set; } = string.Empty;
        [JsonProperty("Foo")] public Dictionary<long, VtSkill_FooEntry>? Foo { get; set; }
        /// <summary>reagent</summary>
        [JsonProperty("reagent")] public XRef<VtItemXCfgId, VtItemXCfg> Reagent { get; set; }
        [JsonProperty("cross-skill1")] public XRef<VtSkillCfgId, VtSkillCfg> CrossSkill1 { get; set; } = new(string.Empty, null);
        [JsonProperty("weapons")] public List<XRef<VtItemXCfgId, VtItemXCfg>>? Weapons { get; set; }
        [JsonProperty("cross-skill2")] public XRef<VtSkillCfgId, VtSkillCfg> CrossSkill2 { get; set; } = new(string.Empty, null);
    }

    // VtSkill_FooEntry represents $.*.Foo.*
    public partial class VtSkill_FooEntry
    {
        /// <summary>X1a</summary>
        [JsonProperty("X1")] public string X1 { get; set; } = string.Empty;
        [JsonProperty("X2")] public Duration X2 { get; set; }
        /// <summary>X5</summary>
        [JsonProperty("X5")] public long X5 { get; set; }
    }

    public partial class VtSkillTable
    {
        public bool TryLookup(VtSkillCfgId cfgId, [NotNullWhen(true)] out VtSkillCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this, "VtSkillTable", out cfg);
        }

        public VtSkillCfg? Lookup(VtSkillCfgId cfgId)
        {
            return ConfigAtlas.Lookup(cfgId, this, "VtSkillTable");
        }

        internal XRef<VtSkillCfgId, VtSkillCfg> RefLookup(VtSkillCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup(cfgId, this, "VtSkillTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(VtSkillCfgIdJsonConverter))]
    [TypeConverter(typeof(VtSkillCfgIdTypeConverter))]
    public partial struct VtSkillCfgId : IEquatable<VtSkillCfgId>, IZero
    {
        public VtSkillCfgId(string value) { Value = value; }
        public static implicit operator VtSkillCfgId(string value) => new() { Value = value };
        public static implicit operator string(VtSkillCfgId obj) => obj.Value ?? string.Empty;

        public override readonly bool Equals(object? obj) => obj is VtSkillCfgId other && Equals(other);
        public readonly bool Equals(VtSkillCfgId other) => (Value ?? string.Empty) == (other.Value ?? string.Empty);
        public override readonly int GetHashCode() => (Value ?? string.Empty).GetHashCode();

        public static bool operator ==(VtSkillCfgId left, VtSkillCfgId right) => left.Equals(right);
        public static bool operator !=(VtSkillCfgId left, VtSkillCfgId right) => !left.Equals(right);

        public override readonly string ToString() => Value ?? string.Empty;
        public bool IsZero => string.IsNullOrEmpty(Value);
    }

    class VtSkillCfgIdJsonConverter : ValueWrapperJsonConverter<VtSkillCfgId, string>
    {
        protected override VtSkillCfgId Create(string value) => value;
        protected override string GetValue(VtSkillCfgId obj) => obj.Value ?? string.Empty;
    }

    class VtSkillCfgIdTypeConverter : ValueWrapperTypeConverter<VtSkillCfgId, string>
    {
        protected override VtSkillCfgId Create(string value) => value;
    }

    public partial class VtSkillTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val is not null) val.Id = key;
            }
        }
    }

    public partial class VtSkillTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                v1?.BindRefs(atlas);
            }
        }
    }

    public partial class VtSkillCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Reagent = atlas.VtItemXTable.RefLookup(Reagent.CfgId);
            CrossSkill1 = atlas.VtSkillTable.RefLookup(CrossSkill1.CfgId);
            if (Weapons is not null)
            {
                for (var i1 = 0; i1 < Weapons.Count; i1++)
                {
                    Weapons[i1] = atlas.VtItemXTable.RefLookup(Weapons[i1].CfgId);
                }
            }
            CrossSkill2 = atlas.VtSkillTable.RefLookup(CrossSkill2.CfgId);
        }
    }

    #endregion
}
