// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/weapon-rune.xlsx

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial struct WeaponRuneCfgId
    {
        public long Value { get; internal set; }
    }

    public partial class WeaponRuneTable : Dictionary<WeaponRuneCfgId, WeaponRuneCfg?> {}

    public partial class WeaponRuneCfg
    {
        [JsonIgnore]
        public WeaponRuneCfgId Id { get; set; }
        [JsonProperty("runeName")]
        public string RuneName { get; set; } = null!;
        [JsonProperty("power")]
        public long Power { get; set; }
    }

    public partial class WeaponRuneTable
    {
        public bool TryLookup(WeaponRuneCfgId cfgId, out WeaponRuneCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgId, this!, "WeaponRuneTable", out cfg);
        }

        public WeaponRuneCfg? Lookup(WeaponRuneCfgId cfgId)
        {
            return ConfigAtlas.Lookup<WeaponRuneCfgId, WeaponRuneCfg>(cfgId, this!, "WeaponRuneTable");
        }

        internal XRef<WeaponRuneCfgId, WeaponRuneCfg> RefLookup(WeaponRuneCfgId cfgId)
        {
            return ConfigAtlas.MakeXRef(cfgId, ConfigAtlas.Lookup<WeaponRuneCfgId, WeaponRuneCfg>(cfgId, this!, "WeaponRuneTable"));
        }
    }

    #region Trifles

    [JsonConverter(typeof(WeaponRuneCfgIdJsonConverter))]
    [TypeConverter(typeof(WeaponRuneCfgIdTypeConverter))]
    public partial struct WeaponRuneCfgId : IEquatable<WeaponRuneCfgId>, IZero
    {
        public static implicit operator WeaponRuneCfgId(long value) => new() { Value = value };
        public static implicit operator long(WeaponRuneCfgId obj) => obj.Value;

        public bool Equals(WeaponRuneCfgId other) => Value == other.Value;
        public override bool Equals(object? obj) => obj is WeaponRuneCfgId other && Equals(other);
        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(WeaponRuneCfgId left, WeaponRuneCfgId right) => left.Value == right.Value;
        public static bool operator !=(WeaponRuneCfgId left, WeaponRuneCfgId right) => left.Value != right.Value;

        public override string ToString() => Value.ToString();
        public bool IsZero => Value == default;
    }

    internal class WeaponRuneCfgIdJsonConverter : ValueWrapperJsonConverter<WeaponRuneCfgId, long>
    {
        protected override WeaponRuneCfgId Create(long value) => value;
        protected override long GetValue(WeaponRuneCfgId obj) => obj.Value;
    }

    internal class WeaponRuneCfgIdTypeConverter : ValueWrapperTypeConverter<WeaponRuneCfgId, long>
    {
        protected override WeaponRuneCfgId Create(long value) => value;
    }

    public partial class WeaponRuneTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    #endregion
}
