// <auto-generated />
// Code generated by (shadop.dev) archmage. DO NOT EDIT.

#nullable enable

namespace Conf.Editor
{
    public static partial class ArchmageEditorTools
    {
        static void RegisterDefaultCfgIdDrawers(ConfigAtlas atlas)
        {
            DropCfgIdDrawer.Initialize(atlas.DropTable, v => $"{v}");
            HeroCfgIdDrawer.Initialize(atlas.HeroTable, v => $"{v}");
            ItemCfgIdDrawer.Initialize(atlas.ItemTable, v => $"{v}");
            MonsterCfgIdDrawer.Initialize(atlas.MonsterTable, v => $"{v}");
            RaceCfgIdDrawer.Initialize(atlas.RaceTable, v => $"{v}");
            RegionCfgIdDrawer.Initialize(atlas.RegionTable, v => $"{v}");
            SkillCfgIdDrawer.Initialize(atlas.SkillTable, v => $"{v}");
        }
    }
}
