// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/drop.xlsx

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(DropCfgId))]
    public class DropCfgIdDrawer : IntCfgIdDrawer<DropCfgId, long>
    {
        public static void Initialize(DropTable tbl, Func<long, string> format) =>
            Initialize("DropTable", tbl.Keys, id => id.Value, format);
    }
}
