// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/hero.xlsx

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(HeroCfgId))]
    public class HeroCfgIdDrawer : IntCfgIdDrawer<HeroCfgId, long>
    {
        public static void Initialize(HeroTable tbl, Func<long, string> format) =>
            Initialize("HeroTable", tbl.Keys, id => id.Value, format);
    }
}
