// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Item

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(ItemCfgId))]
    public class ItemCfgIdDrawer : IntCfgIdDrawer<ItemCfgId, long>
    {
        public static void Initialize(ItemTable tbl, Func<long, string> format) =>
            Initialize("ItemTable", tbl.Keys, id => id.Value, format);
    }
}
