// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Magic

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(MagicCfgId))]
    public class MagicCfgIdDrawer : IntCfgIdDrawer<MagicCfgId, long>
    {
        public static void Initialize(MagicTable tbl, Func<long, string> format) =>
            Initialize("MagicTable", tbl.Keys, id => id.Value, format);
    }
}
