// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/monster.json

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(MonsterCfgId))]
    public class MonsterCfgIdDrawer : IntCfgIdDrawer<MonsterCfgId, long>
    {
        public static void Initialize(MonsterTable tbl, Func<long, string> format) =>
            Initialize("MonsterTable", tbl.Keys, id => id.Value, format);
    }
}
