// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Race

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(RaceCfgId))]
    public class RaceCfgIdDrawer : StrCfgIdDrawer<RaceCfgId>
    {
        public static void Initialize(RaceTable tbl, Func<string, string> format) =>
            Initialize("RaceTable", tbl.Keys, id => id.Value, format);
    }
}
