// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/ref.xlsx

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(RefCfgId))]
    public class RefCfgIdDrawer : IntCfgIdDrawer<RefCfgId, long>
    {
        public static void Initialize(RefTable tbl, Func<long, string> format) =>
            Initialize("RefTable", tbl.Keys, id => id.Value, format);
    }
}
