// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/world.xlsx::Region

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(RegionCfgId))]
    public class RegionCfgIdDrawer : StrCfgIdDrawer<RegionCfgId>
    {
        public static void Initialize(RegionTable tbl, Func<string, string> format) =>
            Initialize("RegionTable", tbl.Keys, id => id.Value, format);
    }
}
