// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source: skill (virtual table)

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(SkillCfgId))]
    public class SkillCfgIdDrawer : StrCfgIdDrawer<SkillCfgId>
    {
        public static void Initialize(SkillTable tbl, Func<string, string> format) =>
            Initialize("SkillTable", tbl.Keys, id => id.Value, format);
    }
}
