// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/sdk/string.xlsx

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(StringCfgId))]
    public class StringCfgIdDrawer : StrCfgIdDrawer<StringCfgId>
    {
        public static void Initialize(StringTable tbl, Func<string, string> format) =>
            Initialize("StringTable", tbl.Keys, id => id.Value, format);
    }
}
