// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtItemX (virtual table)

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(VtItemXCfgId))]
    public class VtItemXCfgIdDrawer : IntCfgIdDrawer<VtItemXCfgId, long>
    {
        public static void Initialize(VtItemXTable tbl, Func<long, string> format) =>
            Initialize("VtItemXTable", tbl.Keys, id => id.Value, format);
    }
}
