// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtQuest (virtual table)

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(VtQuestCfgId))]
    public class VtQuestCfgIdDrawer : IntCfgIdDrawer<VtQuestCfgId, long>
    {
        public static void Initialize(VtQuestTable tbl, Func<long, string> format) =>
            Initialize("VtQuestTable", tbl.Keys, id => id.Value, format);
    }
}
