// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtSkill (virtual table)

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(VtSkillCfgId))]
    public class VtSkillCfgIdDrawer : StrCfgIdDrawer<VtSkillCfgId>
    {
        public static void Initialize(VtSkillTable tbl, Func<string, string> format) =>
            Initialize("VtSkillTable", tbl.Keys, id => id.Value, format);
    }
}
