// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/weapon-rune.xlsx

#nullable enable

using UnityEditor;
using System;
using Shadop.Archmage.Sdk.Editor;

namespace Conf.Editor
{
    [CustomPropertyDrawer(typeof(WeaponRuneCfgId))]
    public class WeaponRuneCfgIdDrawer : IntCfgIdDrawer<WeaponRuneCfgId, long>
    {
        public static void Initialize(WeaponRuneTable tbl, Func<long, string> format) =>
            Initialize("WeaponRuneTable", tbl.Keys, id => id.Value, format);
    }
}
