// Code generated by (shadowopera) archmage. DO NOT EDIT.

using System;
using Shadop.Archmage;

namespace Conf
{
    public readonly struct L10n
    {
        public static Func<I18n>? GetI18n = null;

        readonly string _key;

        public L10n(string key) { _key = key; }

        public bool GetText(string lang, out string? text) => GetI18n!().GetText(_key, lang, out text);
        public string Text(string lang) => GetI18n!().Text(_key, lang);

        public override string ToString() => _key;
    }
}
