// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/clutter/clutter.xlsm::Race

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class RaceTable : Dictionary<string, RaceCfg?>
    {
        // Definition only.
    }

    public partial class RaceCfg
    {
        [JsonIgnore]
        public string ID { get; set; } = null!;
        [JsonProperty("birthplace")]
        public L10n Birthplace { get; set; }
        [JsonProperty("referrer1")]
        public Ref<long, RefCfg> Referrer1 { get; set; }
        [JsonProperty("referrer2")]
        public Ref<string, StringCfg> Referrer2 { get; set; }
        [JsonProperty("heroes1")]
        public List<Ref<long, HeroCfg>>? Heroes1 { get; set; }
        [JsonProperty("heroes2")]
        public List<Ref<long, HeroCfg>>? Heroes2 { get; set; }
    }

    public partial class RaceTable
    {
        public bool TryLookup(string cfgID, out RaceCfg? cfg)
        {
            return ConfigAtlas.TryLookup<string, RaceCfg>(cfgID, this!, "RaceTable", out cfg);
        }

        public RaceCfg? Lookup(string cfgID)
        {
            return ConfigAtlas.Lookup<string, RaceCfg>(cfgID, this!, "RaceTable");
        }

        internal Ref<string, RaceCfg> RefLookup(string cfgID)
        {
            return ConfigAtlas.MakeRef(cfgID, ConfigAtlas.Lookup<string, RaceCfg>(cfgID, this!, "RaceTable"));
        }
    }

    #region Trifles

    public partial class RaceTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.ID = key;
            }
        }
    }

    public partial class RaceTable : IRefBinder
    {
        void IRefBinder.BindRefs(ConfigAtlas atlas)
        {
            foreach (var v1 in this.Values)
            {
                if (v1 != null)
                    v1.BindRefs(atlas);
            }
        }
    }

    public partial class RaceCfg
    {
        internal void BindRefs(ConfigAtlas atlas)
        {
            Referrer1 = atlas.RefTable.RefLookup(Referrer1.RawValue);
            Referrer2 = atlas.StringTable.RefLookup(Referrer2.RawValue);
            if (Heroes1 != null)
            {
                for (var i = 0; i < Heroes1.Count; i++)
                {
                    Heroes1[i] = atlas.HeroTable.RefLookup(Heroes1[i].RawValue);
                }
            }
            if (Heroes2 != null)
            {
                for (var i = 0; i < Heroes2.Count; i++)
                {
                    Heroes2[i] = atlas.HeroTable.RefLookup(Heroes2[i].RawValue);
                }
            }
        }
    }

    #endregion
}
