// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: vtSkill (virtual table)

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class VtSkillTable : Dictionary<long, VtSkillCfg?>
    {
        // Definition only.
    }

    public partial class VtSkillCfg
    {
        [JsonIgnore]
        public long Id { get; set; }
        [JsonProperty("name")]
        public string Name { get; set; } = null!;
        [JsonProperty("class")]
        public string Class { get; set; } = null!;
        [JsonProperty("Foo")]
        public Dictionary<long, VtSkill_FooEntry>? Foo { get; set; }
        /// <summary>
        /// reagent
        /// </summary>
        [JsonProperty("reagent")]
        public long Reagent { get; set; }
        [JsonProperty("weapons")]
        public List<long>? Weapons { get; set; }
    }

    // VtSkill_FooEntry represents $.*.Foo.*
    public partial class VtSkill_FooEntry
    {
        /// <summary>
        /// X1a
        /// </summary>
        [JsonProperty("X1")]
        public string X1 { get; set; } = null!;
        [JsonProperty("X2")]
        public Duration X2 { get; set; }
        /// <summary>
        /// X5
        /// </summary>
        [JsonProperty("X5")]
        public long X5 { get; set; }
    }

    public partial class VtSkillTable
    {
        public bool TryLookup(long cfgID, out VtSkillCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgID, this!, "VtSkillTable", out cfg);
        }

        public VtSkillCfg? Lookup(long cfgID)
        {
            return ConfigAtlas.Lookup<long, VtSkillCfg>(cfgID, this!, "VtSkillTable");
        }

        internal Ref<long, VtSkillCfg> RefLookup(long cfgID)
        {
            return ConfigAtlas.MakeRef(cfgID, ConfigAtlas.Lookup<long, VtSkillCfg>(cfgID, this!, "VtSkillTable"));
        }
    }

    #region Trifles

    public partial class VtSkillTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.Id = key;
            }
        }
    }

    #endregion
}
