// Code generated by (shadowopera) archmage. DO NOT EDIT.
// Source: examples/conf/weapon-rune.xlsx

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Shadop.Archmage;

namespace Conf
{
    public partial class WeaponRuneTable : Dictionary<long, WeaponRuneCfg?>
    {
        // Definition only.
    }

    public partial class WeaponRuneCfg
    {
        [JsonIgnore]
        public long ID { get; set; }
        [JsonProperty("runeName")]
        public string RuneName { get; set; } = null!;
        [JsonProperty("power")]
        public long Power { get; set; }
    }

    public partial class WeaponRuneTable
    {
        public bool TryLookup(long cfgID, out WeaponRuneCfg? cfg)
        {
            return ConfigAtlas.TryLookup(cfgID, this!, "WeaponRuneTable", out cfg);
        }

        public WeaponRuneCfg? Lookup(long cfgID)
        {
            return ConfigAtlas.Lookup<long, WeaponRuneCfg>(cfgID, this!, "WeaponRuneTable");
        }

        internal Ref<long, WeaponRuneCfg> RefLookup(long cfgID)
        {
            return ConfigAtlas.MakeRef(cfgID, ConfigAtlas.Lookup<long, WeaponRuneCfg>(cfgID, this!, "WeaponRuneTable"));
        }
    }

    #region Trifles

    public partial class WeaponRuneTable : IApplyKeys
    {
        void IApplyKeys.ApplyKeys()
        {
            foreach (var (key, val) in this)
            {
                if (val != null) val.ID = key;
            }
        }
    }

    #endregion
}
