using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Conf;
using Shadop.Archmage.Sdk;
using UnityEngine;
using UnityEngine.AddressableAssets;
using UnityEngine.Networking;
using UnityEngine.ResourceManagement.AsyncOperations;
using UnityEngine.ResourceManagement.ResourceProviders;

// Probes how Task.Run and the loader behave on the current player platform.
// The case to run comes from the page URL on WebGL (index.html?case=<name>) and from the launch
// intent's "case" extra on Android (am start ... -e case <name>).
// Every line starts with [Probe]; the last line is "[Probe] DONE".
public class PlatformProbe : MonoBehaviour
{
    const int MaxFrames = 600;

    // The files that atlas.json in Assets/Configs names, with balance=hard.
    static readonly string[] ConfigFiles =
    {
        "chapter.json", "drop.json", "hero.json", "item.json", "monster.json", "race.json", "region.json",
        "route.json", "balance.hard.json", "game.json",
        "vtbl/skill-magic.json", "vtbl/skill-melee.json", "vtbl/skill-passive.json",
    };

    // Generated by PlatformProbeBuild before the build and deleted afterwards.
    public const string BulkDir = "Assets/PlatformProbe/Bulk";
    public const int BulkCount = 100;
    // 100 files of about 50KB each, in a group of their own so that they do not enlarge the other cases' bundle.
    public const string LargeDir = "Assets/PlatformProbe/Large";

    int _mainThread;

    async Awaitable Start()
    {
        _mainThread = Environment.CurrentManagedThreadId;
        var name = GetCase();
        Log($"case={name} platform={Application.platform} mainThread={_mainThread}");

        // Let the first frame finish so that frame counts start from a steady state.
        await Awaitable.NextFrameAsync();

        try
        {
            switch (name)
            {
                case "taskrun":
                    await ProbeTaskRun();
                    break;
                case "taskrun-wait":
                    ProbeTaskRunWait();
                    break;
                case "sync-resources":
                    ProbeSyncResources();
                    break;
                case "async-resources":
                    await ProbeAsync(new UnityResourcesFS(), "StaticConfigs");
                    break;
                case "async-streaming":
                    await ProbeAsync(new UnityStreamingAssetsFS(), "StreamingConfigs");
                    break;
                case "async-addressables":
                    await ProbeAsync(new UnityAddressablesFS(), "Assets/Configs");
                    break;
                case "streaming-read":
                    await ProbeStreamingRead();
                    break;
                case "streaming-override":
                    await ProbeAsync(new UnityStreamingAssetsFS(), "StreamingConfigs", "StreamingConfigOverrides");
                    break;
                case "streaming-override-missing":
                    await ProbeAsync(new UnityStreamingAssetsFS(), "StreamingConfigs", "NoSuchOverrides");
                    break;
                default:
                    if (name.StartsWith("addr-", StringComparison.Ordinal))
                        await ProbeAddressablesRead(name);
                    else
                        Log($"RESULT unknown case: {name}");
                    break;
            }
        }
        catch (Exception ex)
        {
            Log($"RESULT exception: {ex}");
        }

        Log("DONE");
    }

    // Does the delegate run inline, later on the main thread, on another thread, or never?
    async Awaitable ProbeTaskRun()
    {
        // Time.frameCount may be read only on the main thread, so the delegate records just its thread.
        var startFrame = Time.frameCount;
        var ranThread = -1;
        var task = Task.Run(() => Volatile.Write(ref ranThread, Environment.CurrentManagedThreadId));
        Log($"after Task.Run: ran={Volatile.Read(ref ranThread) >= 0} status={task.Status}");

        while (!task.IsCompleted && Time.frameCount - startFrame < MaxFrames)
            await Awaitable.NextFrameAsync();

        if (!task.IsCompleted)
        {
            Log($"RESULT never ran within {MaxFrames} frames, status={task.Status}");
            return;
        }
        Log($"RESULT ran on thread {ranThread} (main={ranThread == _mainThread}), " +
            $"completed after {Time.frameCount - startFrame} frames, status={task.Status}");

        // Does an await on a Task.Run task resume?
        startFrame = Time.frameCount;
        var awaitTask = AwaitTaskRun();
        while (!awaitTask.IsCompleted && Time.frameCount - startFrame < MaxFrames)
            await Awaitable.NextFrameAsync();
        Log(awaitTask.IsCompleted
            ? $"RESULT await Task.Run resumed after {Time.frameCount - startFrame} frames, status={awaitTask.Status}"
            : $"RESULT await Task.Run did not resume within {MaxFrames} frames");
    }

    static async Task AwaitTaskRun()
    {
        await Task.Run(() => Thread.SpinWait(10));
    }

    // Blocks the main thread on a Task.Run task, as the synchronous loader does.
    void ProbeTaskRunWait()
    {
        var task = Task.Run(() => Thread.SpinWait(10));
        Log("before Task.WaitAll");
        Task.WaitAll(task);
        Log($"RESULT Task.WaitAll returned, status={task.Status}");
    }

    void ProbeSyncResources()
    {
        var atlas = new ConfigAtlas();
        Log("before LoadAtlas");
        Archmage.LoadAtlas("StaticConfigs/atlas.json", "StaticConfigs", atlas, NewOptions(new UnityResourcesFS()));
        Log($"RESULT LoadAtlas returned, heroes={atlas.HeroTable.Count}");
    }

    // How does a StreamingAssets read fail for an existing file, a missing file and a missing directory?
    async Task ProbeStreamingRead()
    {
        Log($"streamingAssetsPath={Application.streamingAssetsPath}");
        foreach (var path in new[] { "StreamingConfigs/hero.json", "StreamingConfigs/nope.json", "NoSuchDir/nope.json" })
        {
            var uri = Application.streamingAssetsPath + "/" + path;
            if (!uri.Contains("://"))
                uri = "file://" + uri;
            using (var request = UnityWebRequest.Get(uri))
            {
                await request.SendWebRequest();
                Log($"RESULT raw {path}: result={request.result} responseCode={request.responseCode} " +
                    $"error={request.error} bytes={request.downloadHandler.data?.Length ?? -1}");
            }

            try
            {
                var bytes = await new UnityStreamingAssetsFS().ReadAllBytesAsync(path);
                Log($"RESULT fs {path}: {bytes.Length} bytes");
            }
            catch (Exception ex)
            {
                Log($"RESULT fs {path}: {ex.GetType().Name}: {ex.Message}");
            }
        }
    }

    async Task ProbeAsync(IFS fs, string cfgRoot, string overrideRoot = null)
    {
        var atlas = new ConfigAtlas();
        var timingFS = new TimingFS(fs);
        var options = NewOptions(timingFS);
        if (overrideRoot != null)
            options.WithOverrideRoot(overrideRoot + "/1").WithOverrideRoot(overrideRoot + "/2");
        var startFrame = Time.frameCount;
        var task = Archmage.LoadAtlasAsync($"{cfgRoot}/atlas.json", cfgRoot, atlas, options);
        while (!task.IsCompleted && Time.frameCount - startFrame < MaxFrames)
            await Awaitable.NextFrameAsync();

        if (!task.IsCompleted)
        {
            Log($"RESULT LoadAtlasAsync did not complete within {MaxFrames} frames");
            return;
        }
        await task;
        Log($"RESULT LoadAtlasAsync completed after {Time.frameCount - startFrame} frames, heroes={atlas.HeroTable.Count}");
        foreach (var r in timingFS.Reads)
            Log($"read {r.Path}: start={r.Start - startFrame} end={r.End - startFrame}");
    }

    // Compares ways of reading many files through Addressables. The case name is
    // addr-<each|bundle-sync|bundle-async>-<13|100|large>.
    async Awaitable ProbeAddressablesRead(string name)
    {
        var i = name.LastIndexOf('-');
        var variant = name.Substring("addr-".Length, i - "addr-".Length);
        var paths = name.Substring(i + 1) switch
        {
            "100" => Enumerable.Range(0, BulkCount).Select(n => BulkFile(BulkDir, n)).ToArray(),
            "large" => Enumerable.Range(0, BulkCount).Select(n => BulkFile(LargeDir, n)).ToArray(),
            _ => ConfigFiles.Select(f => "Assets/Configs/" + f).ToArray(),
        };

        // Keep initialization out of the measurement.
        await Addressables.InitializeAsync().Task;

        var startFrame = Time.frameCount;
        var startTime = Time.realtimeSinceStartupAsDouble;
        Task<int> task;
        switch (variant)
        {
            case "each":
                task = ReadEach(paths);
                break;
            case "bundle-sync":
            case "bundle-async":
                task = ReadFromBundle(paths, variant);
                break;
            default:
                Log($"RESULT unknown variant: {variant}");
                return;
        }

        // A bundle load is counted when the number of loaded bundles goes from 0 to non-zero.
        var bundleLoads = 0;
        var bundlesLoaded = false;
        var longestFrame = Time.realtimeSinceStartupAsDouble - startTime;
        var frameStart = Time.realtimeSinceStartupAsDouble;
        while (true)
        {
            var loaded = AssetBundle.GetAllLoadedAssetBundles().Any();
            if (loaded && !bundlesLoaded)
                bundleLoads++;
            bundlesLoaded = loaded;

            if (task.IsCompleted || Time.frameCount - startFrame >= MaxFrames)
                break;
            await Awaitable.NextFrameAsync();
            var now = Time.realtimeSinceStartupAsDouble;
            longestFrame = Math.Max(longestFrame, now - frameStart);
            frameStart = now;
        }
        var totalMs = (Time.realtimeSinceStartupAsDouble - startTime) * 1000;

        if (!task.IsCompleted)
        {
            Log($"RESULT {name} did not complete within {MaxFrames} frames: bundleLoads={bundleLoads}");
            return;
        }
        var bytes = await task;
        Log($"RESULT {name}: files={paths.Length} bytes={bytes} frames={Time.frameCount - startFrame} " +
            $"totalMs={totalMs:F1} longestFrameMs={longestFrame * 1000:F1} bundleLoads={bundleLoads}");
    }

    public static string BulkFile(string dir, int i) => $"{dir}/file_{i:D3}.json";

    // Reads each file through UnityAddressablesFS, at most 32 at a time, with the loader's windowing:
    // wait for any running read to finish before starting another.
    static async Task<int> ReadEach(string[] paths)
    {
        var fs = new UnityAddressablesFS();
        var total = 0;
        var running = new List<Task<byte[]>>();
        foreach (var path in paths)
        {
            if (running.Count >= 32)
            {
                var done = await Task.WhenAny(running);
                running.Remove(done);
                total += done.Result.Length;
            }
            running.Add(fs.ReadAllBytesAsync(path));
        }
        return total + (await Task.WhenAll(running)).Sum(bytes => bytes.Length);
    }

    // Loads the bundle that holds the files through Addressables, then reads the files from the AssetBundle
    // directly: with a synchronous LoadAsset per file (bundle-sync), or with one LoadAssetAsync per file, all
    // started at once (bundle-async). All files must be in one bundle.
    static async Task<int> ReadFromBundle(string[] paths, string variant)
    {
        var rm = Addressables.ResourceManager;
        var locationsHandle = Addressables.LoadResourceLocationsAsync(paths, Addressables.MergeMode.Union, typeof(TextAsset));
        try
        {
            if (!locationsHandle.IsDone)
                await locationsHandle.Task;
            if (locationsHandle.Status != AsyncOperationStatus.Succeeded)
                throw new IOException("LoadResourceLocationsAsync failed.", locationsHandle.OperationException);
            var locations = locationsHandle.Result;

            var bundleHandle = rm.ProvideResource<IAssetBundleResource>(locations[0].Dependencies[0]);
            try
            {
                if (!bundleHandle.IsDone)
                    await bundleHandle.Task;
                if (bundleHandle.Status != AsyncOperationStatus.Succeeded)
                    throw new IOException("Failed to load the bundle.", bundleHandle.OperationException);
                var bundle = bundleHandle.Result.GetAssetBundle();

                if (variant == "bundle-async")
                {
                    var startFrame = Time.frameCount;
                    var endFrames = new int[locations.Count];
                    var reads = locations.Select((location, n) =>
                    {
                        var tcs = new TaskCompletionSource<int>();
                        var request = bundle.LoadAssetAsync<TextAsset>(rm.TransformInternalId(location));
                        request.completed += _ =>
                        {
                            endFrames[n] = Time.frameCount - startFrame;
                            tcs.SetResult(((TextAsset)request.asset).bytes.Length);
                        };
                        return tcs.Task;
                    }).ToArray();
                    var lengths = await Task.WhenAll(reads);
                    Log($"bundle-async completion frames: {string.Join(",", endFrames)}");
                    return lengths.Sum();
                }

                var total = 0;
                foreach (var location in locations)
                    total += bundle.LoadAsset<TextAsset>(rm.TransformInternalId(location)).bytes.Length;
                return total;
            }
            finally
            {
                bundleHandle.Release();
            }
        }
        finally
        {
            Addressables.Release(locationsHandle);
        }
    }

    // Records the frame at which each read starts and the frame at which it completes.
    class TimingFS : IFS
    {
        readonly IFS _inner;

        public TimingFS(IFS inner) => _inner = inner;

        public System.Collections.Generic.List<(string Path, int Start, int End)> Reads { get; } = new();

        public byte[] ReadAllBytes(string path) => _inner.ReadAllBytes(path);

        public async Task<byte[]> ReadAllBytesAsync(string path, CancellationToken cancellationToken = default)
        {
            var start = Time.frameCount;
            try
            {
                return await _inner.ReadAllBytesAsync(path, cancellationToken);
            }
            finally
            {
                Reads.Add((path, start, Time.frameCount));
            }
        }

        public bool FileExists(string path) => _inner.FileExists(path);

        public bool DirectoryExists(string path) => _inner.DirectoryExists(path);
    }

    static AtlasOptions NewOptions(IFS fs)
    {
        return new AtlasOptions()
            .WithLogger(new UnityAtlasLogger())
            .WithJsonSettings(UnityJsonSettingsFactory.Create())
            .WithFS(fs)
            .WithVariant("balance", "hard");
    }

    static string GetCase()
    {
#if UNITY_ANDROID && !UNITY_EDITOR
        using (var player = new AndroidJavaClass("com.unity3d.player.UnityPlayer"))
        using (var activity = player.GetStatic<AndroidJavaObject>("currentActivity"))
        using (var intent = activity.Call<AndroidJavaObject>("getIntent"))
            return intent.Call<string>("getStringExtra", "case") ?? "taskrun";
#else
        var url = Application.absoluteURL;
        var i = url.IndexOf("case=", StringComparison.Ordinal);
        if (i < 0)
            return "taskrun";
        var s = url.Substring(i + "case=".Length);
        var end = s.IndexOfAny(new[] { '&', '#' });
        return end < 0 ? s : s.Substring(0, end);
#endif
    }

    static void Log(string msg)
    {
        Debug.Log($"[Probe] frame={Time.frameCount} thread={Environment.CurrentManagedThreadId} {msg}");
    }
}
