// This file was initially generated by (shadowopera) archmage.
// Feel free to edit this file as it will not be overwritten in subsequent runs.

#nullable enable

using UnityEditor;
using UnityEngine;
using System;
using Shadop.Archmage.Sdk;

namespace Conf.Editor
{
    public static partial class ArchmageEditorTools
    {
        [MenuItem("Tools/Reload Game Configs for Editor", true)]
        static bool ValidateReloadGameConfigs() => !EditorApplication.isPlayingOrWillChangePlaymode;

        [MenuItem("Tools/Reload Game Configs for Editor")]
        public static void ReloadGameConfigs()
        {
            EditorUtility.DisplayProgressBar("Loading Game Configs", "Loading...", 0f);
            Initialize(clear: EditorUtility.ClearProgressBar);
        }

        [InitializeOnLoadMethod]
        public static void AutoLoadGameConfigs()
        {
            // NOTE: this relies on domain reload. With Enter Play Mode Options -> Reload Domain
            // disabled, the method does not run when entering play mode, and the drawers keep
            // pointing at the atlas loaded for the editor.
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                // Assumes that the game loads the config atlas and sets ConfigAtlas.Instance on its own;
                // wait for that instead of loading a second copy here.
                EditorApplication.update -= MonitorRuntimeAtlasInstance;
                EditorApplication.update += MonitorRuntimeAtlasInstance;
                return;
            }
            Initialize();
        }

        static void MonitorRuntimeAtlasInstance()
        {
            var atlas = ConfigAtlas.Instance;
            if (atlas != null)
            {
                EditorApplication.update -= MonitorRuntimeAtlasInstance;
                try
                {
                    InitializeCfgIdDrawers(atlas);
                    RepaintEditorWindows();
                    Debug.Log("<archmage> CfgIdDrawerManager.Initialize succeeded (Runtime Bound).");
                }
                catch (Exception ex)
                {
                    Debug.LogError($"<archmage> CfgIdDrawerManager.Initialize failed: {ex}");
                }
                return;
            }

            if (!EditorApplication.isPlayingOrWillChangePlaymode)
            {
                // Play mode ended before the runtime atlas was ready; load one for the editor.
                EditorApplication.update -= MonitorRuntimeAtlasInstance;
                Initialize();
            }
        }

        static void Initialize(IProgress<AtlasLoadEvent>? progress = null, Action? clear = null)
        {
            try
            {
                ConfLoader.DirectAccessDemo(progress);

                var atlas = ConfigAtlas.Instance;
                if (atlas == null)
                {
                    Debug.LogWarning("<archmage> CfgIdDrawerManager.Initialize failed: ConfigAtlas.Instance is null.");
                    return;
                }

                InitializeCfgIdDrawers(atlas);
                RepaintEditorWindows();
                Debug.Log("<archmage> CfgIdDrawerManager.Initialize succeeded.");
            }
            catch (Exception ex)
            {
                Debug.LogError($"<archmage> CfgIdDrawerManager.Initialize failed: {ex}");
            }
            finally
            {
                clear?.Invoke();
            }
        }

        static void RepaintEditorWindows()
        {
            // The inspector types (InspectorWindow, PropertyEditor) are internal, and matching
            // them by name misses the floating ones, so repaint everything.
            foreach (var w in Resources.FindObjectsOfTypeAll<EditorWindow>())
                w.Repaint();
        }

        static void InitializeCfgIdDrawers(ConfigAtlas atlas)
        {
            // Initialize XxxCfgIdDrawer on demand
            HeroCfgIdDrawer.Initialize(atlas.HeroTable, v => $"{v} ({new HeroCfgId(v).Cfg.HeroName.Text})");
        }
    }
}
