// Code generated by (shadop.dev) archmage. DO NOT EDIT.
// Source File: examples/conf/sdk/sdk.enum.yml
// Source File MD5: 737dea217ecdbcfea465569008dd7a54

#nullable enable

/*
 * Enums for the SDK integration test data.
 */

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Conf.Enums
{
    #region HeroClass

    /// <summary>
    /// Playable hero classes.
    /// </summary>
    public enum HeroClass : int
    {
        None = 0,
        Warrior = 1,
        Mage = 2,
        Ranger = 3,
        Priest = 4,
    }

    public static partial class HeroClassExtensions
    {
        static readonly Dictionary<HeroClass, string> _enumNameMap = new()
        {
            { HeroClass.None, "None" },
            { HeroClass.Warrior, "Warrior" },
            { HeroClass.Mage, "Mage" },
            { HeroClass.Ranger, "Ranger" },
            { HeroClass.Priest, "Priest" },
        };

        static readonly Dictionary<string, HeroClass> _insensitiveNameEnumMap = new()
        {
            { "none", HeroClass.None },
            { "warrior", HeroClass.Warrior },
            { "mage", HeroClass.Mage },
            { "ranger", HeroClass.Ranger },
            { "priest", HeroClass.Priest },
        };

        static readonly HeroClass[] _enumValues =
        {
            HeroClass.None,
            HeroClass.Warrior,
            HeroClass.Mage,
            HeroClass.Ranger,
            HeroClass.Priest,
        };

        static readonly Dictionary<HeroClass, string> _l10nKeyMap = new()
        {
            { HeroClass.Warrior, "enum::HeroClass.Warrior" },
            { HeroClass.Mage, "enum::HeroClass.Mage" },
        };

        public static IReadOnlyList<HeroClass> AllValues()
        {
            return _enumValues;
        }

        public static void Parse(this ref HeroClass x, string str)
        {
            x = Parse(str);
        }

        public static HeroClass Parse(string str)
        {
            if (str == null)
                throw new ArgumentException("HeroClass: str is null");
            str = str.Trim();
            if (string.IsNullOrEmpty(str))
                throw new ArgumentException("HeroClass: str is empty or whitespace");

            var lower = str.ToLowerInvariant();
            if (_insensitiveNameEnumMap.TryGetValue(lower, out var v))
                return v;

            var s = str;
            if (lower.StartsWith("heroclass(") && lower.EndsWith(')'))
                s = str.Substring(10, str.Length - 11);
            long n;
            try
            {
                var negative = s.StartsWith('-');
                if (negative)
                    s = s.Substring(1);
                n = s.StartsWith("0x", StringComparison.OrdinalIgnoreCase) ?
                    long.Parse(s.Substring(2), NumberStyles.AllowHexSpecifier) :
                    long.Parse(s);
                n = negative ? -n : n;
            }
            catch (Exception ex)
            {
                throw new ArgumentException($"HeroClass: invalid value: {str}", ex);
            }

            if (n < -2147483648 || n > 2147483647)
                throw new OverflowException($"HeroClass: {n} is out of range");
            return (HeroClass)n;
        }

        public static bool IsValid(this HeroClass x)
        {
            return _enumNameMap.ContainsKey(x);
        }

        public static string GetEnumString(this HeroClass x)
        {
            if (_enumNameMap.TryGetValue(x, out var str))
                return str;
            return $"HeroClass({(int)x})";
        }

        public static string GetL10nKey(this HeroClass x)
        {
            if (_l10nKeyMap.TryGetValue(x, out var key))
                return key;
            return string.Empty;
        }
    }

    #endregion

    #region Rarity

    public enum Rarity : byte
    {
        Common = 0,
        Uncommon = 1,
        Rare = 2,
        Epic = 3,
        Legendary = 4,
    }

    public static partial class RarityExtensions
    {
        static readonly Dictionary<Rarity, string> _enumNameMap = new()
        {
            { Rarity.Common, "Common" },
            { Rarity.Uncommon, "Uncommon" },
            { Rarity.Rare, "Rare" },
            { Rarity.Epic, "Epic" },
            { Rarity.Legendary, "Legendary" },
        };

        static readonly Dictionary<string, Rarity> _insensitiveNameEnumMap = new()
        {
            { "common", Rarity.Common },
            { "uncommon", Rarity.Uncommon },
            { "rare", Rarity.Rare },
            { "epic", Rarity.Epic },
            { "legendary", Rarity.Legendary },
        };

        static readonly Rarity[] _enumValues =
        {
            Rarity.Common,
            Rarity.Uncommon,
            Rarity.Rare,
            Rarity.Epic,
            Rarity.Legendary,
        };

        public static IReadOnlyList<Rarity> AllValues()
        {
            return _enumValues;
        }

        public static void Parse(this ref Rarity x, string str)
        {
            x = Parse(str);
        }

        public static Rarity Parse(string str)
        {
            if (str == null)
                throw new ArgumentException("Rarity: str is null");
            str = str.Trim();
            if (string.IsNullOrEmpty(str))
                throw new ArgumentException("Rarity: str is empty or whitespace");

            var lower = str.ToLowerInvariant();
            if (_insensitiveNameEnumMap.TryGetValue(lower, out var v))
                return v;

            var s = str;
            if (lower.StartsWith("rarity(") && lower.EndsWith(')'))
                s = str.Substring(7, str.Length - 8);
            ulong n;
            try
            {
                n = s.StartsWith("0x", StringComparison.OrdinalIgnoreCase) ?
                    ulong.Parse(s.Substring(2), NumberStyles.AllowHexSpecifier) :
                    ulong.Parse(s);
            }
            catch (Exception ex)
            {
                throw new ArgumentException($"Rarity: invalid value: {str}", ex);
            }

            if (n > 255)
                throw new OverflowException($"Rarity: {n} is out of range");
            return (Rarity)n;
        }

        public static bool IsValid(this Rarity x)
        {
            return _enumNameMap.ContainsKey(x);
        }

        public static string GetEnumString(this Rarity x)
        {
            if (_enumNameMap.TryGetValue(x, out var str))
                return str;
            return $"Rarity({(byte)x})";
        }
    }

    #endregion

    #region Element

    [Flags]
    public enum Element : ushort
    {
        None = 0x0,
        Fire = 0x1,
        Water = 0x2,
        Earth = 0x4,
        Wind = 0x8,
        Holy = 0x10,
        Shadow = 0x20,
    }

    public static partial class ElementExtensions
    {
        static readonly Dictionary<Element, string> _enumNameMap = new()
        {
            { Element.None, "None" },
            { Element.Fire, "Fire" },
            { Element.Water, "Water" },
            { Element.Earth, "Earth" },
            { Element.Wind, "Wind" },
            { Element.Holy, "Holy" },
            { Element.Shadow, "Shadow" },
        };

        static readonly Dictionary<string, Element> _insensitiveNameEnumMap = new()
        {
            { "none", Element.None },
            { "fire", Element.Fire },
            { "water", Element.Water },
            { "earth", Element.Earth },
            { "wind", Element.Wind },
            { "holy", Element.Holy },
            { "shadow", Element.Shadow },
        };

        static readonly Element[] _enumValues =
        {
            Element.None,
            Element.Fire,
            Element.Water,
            Element.Earth,
            Element.Wind,
            Element.Holy,
            Element.Shadow,
        };

        public static IReadOnlyList<Element> AllValues()
        {
            return _enumValues;
        }

        static Element ParseBitflags(string str, string raw)
        {
            Element res = 0;
            foreach (var x in str.Split(','))
            {
                var trimmed = x.Trim();
                if (_insensitiveNameEnumMap.TryGetValue(trimmed, out var v))
                    res |= v;
                else
                    throw new ArgumentException($"Element: invalid value: {raw}");
            }

            return res;
        }

        public static void Parse(this ref Element x, string str)
        {
            x = Parse(str);
        }

        public static Element Parse(string str)
        {
            if (str == null)
                throw new ArgumentException("Element: str is null");
            str = str.Trim();
            if (string.IsNullOrEmpty(str))
                throw new ArgumentException("Element: str is empty or whitespace");

            var lower = str.ToLowerInvariant();
            if (_insensitiveNameEnumMap.TryGetValue(lower, out var v))
                return v;

            if (str.IndexOf(',') >= 0)
                return ParseBitflags(lower, str);

            var s = str;
            if (lower.StartsWith("element(") && lower.EndsWith(')'))
                s = str.Substring(8, str.Length - 9);
            ulong n;
            try
            {
                n = s.StartsWith("0x", StringComparison.OrdinalIgnoreCase) ?
                    ulong.Parse(s.Substring(2), NumberStyles.AllowHexSpecifier) :
                    ulong.Parse(s);
            }
            catch (Exception ex)
            {
                throw new ArgumentException($"Element: invalid value: {str}", ex);
            }

            if (n > 65535)
                throw new OverflowException($"Element: {n} is out of range");
            return (Element)n;
        }

        public static bool IsValid(this Element x)
        {
            if (_enumNameMap.ContainsKey(x))
                return true;
            for (var i = _enumValues.Length - 1; i >= 0 && x != 0; i--)
            {
                var v = _enumValues[i];
                if ((x & v) == v)
                    x &= ~v;
            }
            return x == 0;
        }

        public static string GetEnumString(this Element x)
        {
            if (_enumNameMap.TryGetValue(x, out var str))
                return str;

            if (x.IsValid())
            {
                var flags = new List<Element>();
                Element v;
                var i = _enumValues.Length - 1;
                for (; i >= 0 && x != 0; i--)
                {
                    v = _enumValues[i];
                    if (v != 0)
                    {
                        if ((x & v) == v)
                        {
                            x &= ~v;
                            flags.Add(v);
                        }
                    }
                }

                var sb = new StringBuilder();
                i = flags.Count - 1;
                v = flags[i];
                sb.Append(_enumNameMap[v]);
                for (i--; i >= 0; i--)
                {
                    v = flags[i];
                    sb.Append(", ");
                    sb.Append(_enumNameMap[v]);
                }

                return sb.ToString();
            }

            return $"Element({(ushort)x})";
        }
    }

    #endregion

}
